### ISSUE TITLE
"Â" inserted in citations

### ISSUE THREAD

**Issue by dstillman** [Juris-M/citeproc-js#1]
(First!)

I couldn't reproduce this, but it seemed to happen for a user when we upgraded from citeproc-js 1.1.60 to 1.1.71 and go away when we reverted:

https://forums.zotero.org/discussion/57309/

**Comment by fbennett** [comment]
That looks like an unescaped non-breaking space. We had that long ago, it only shows up in RTF output. Probably in the work I did on the output routine in api_cite.js, I missed a txt_esc() where one was needed. I'll take a look after morning coffee.

**Comment by fbennett** [comment]
I've cleaned up the test framework a bit, and enabled tests of RTF output, with a "-rtf" extension on the test-fixture MODE tag. Here is a test that exposes the fault:

https://github.com/citation-style-language/test-suite/blob/master/processor-tests/humans/bugreports_NonBreakingSpaceJoinFail.txt

Should be quick to fix.

**Comment by fbennett** [comment]
There you go. Fixed by 04f2f08
