### ISSUE TITLE
Issue with civil law case law title in single citation

### ISSUE THREAD

**Issue by f-mb** [Juris-M/citeproc-js#10]
**Transferring https://github.com/zotero/zotero/issues/893 here.**

Hi,

When you cite two (or more) "civil law case law" in a single citation, except for the first, court name and date are omitted.

> **Individual Citations :**
> CJCE, 31 mai 1978, C-102/77, Hoffmann-La Roche / Centrafarm, Rec. 1978.1139.
> CJCE, 17 octobre 1990, C-10/89, CNL-SUCAL / HAG (HAG II), Rec. 1990.I‑3711.
> (FYI: `court`, `date`, `docket number`, `short title`, `reporter` `reporter volume`.`first page`.)
> 
> **Single Citation :**
> CJCE, 31 mai 1978, C-102/77, Hoffmann-La Roche / Centrafarm, Rec. 1978.1139; CNL-SUCAL / HAG (HAG II), Rec. 1990.I‑3711.
> 
> **Should be :**
> CJCE, 31 mai 1978, C-102/77, Hoffmann-La Roche / Centrafarm, Rec. 1978.1139; **CJCE, 17 octobre 1990, C-10/89,** CNL-SUCAL / HAG (HAG II), Rec. 1990.I‑3711.

I think the issue is with citeproc.js around lines 4197-4203 [edit: now around 5224-5225].

I know there is a hook with for case. Multiple citations of a case law items with the same title will be merged into one.

I guess the issue is that every "civil law case law" has technically an identical title : ""/false. 
(reminder: civil Law format, in Zotero at least, is created by omitting the `title` field in favour of the `short title` field)

A fix would be for citeproc to first check if there is any title at all...

Thank you.

**Comment by f-mb** [comment]
I think the solution would be at line 5224:
`if (title !== "" && type === "legal_case" && id !== lastID && position) {`
where `title !== ""` test if title is empty (similar to the test at 10121)

**Comment by fbennett** [comment]
Florian (@f-mb): Sorry for  the very long delay in getting back. I would like to straighten this out. Two belated questions to set up a test:
* Would you have reference data to hand (exported in CSL JSON format)?
* Which style should be used?
