### ISSUE TITLE
Subdivided bibliographies

### ISSUE THREAD

**Issue by denismaier** [Juris-M/citeproc-js#104]
I would be great if we could produce subdivided bibliographies.

I am not sure if this is a issue for a) citeproc, b) the calling application, c) both.

**Comment by fbennett** [comment]
Citeproc has a pretty flexible, largely unused mechanism for controlling the output of a bibliography call. We drew on that recently to implement the new `But support in calling applications would be complicated, with the need to supply headers and other stuff.

We can still produce bibs sorted into sections. User can then divide them up manually at the last stage, after stripping codes in a copy of the MS. It's not super smooth (but OTOH the last stage of MS preparation is never smooth anyway.)

**Comment by demai** [comment]
Is here missing something; "We drew on that recently to implement the new `But support in calling applications would be complicated." (the new what?)

Ok, this is actually more related to calling applications than to citeproc, right? 

What parts of the output control mechanism are unused at the moment? What would be possible?

So, at the moment we need to rely on the general CSL sort mechanism. Indeed, the final steps are always a bit messy, but I was hoping that one part of this could be taken out of the equation.

**Comment by fbennett** [comment]
I'll dig the documentation on it out of the old manual tomorrow and put it
on ReadTheDocs. If I forget, feel free to ping me.

The missing but was "exclude-types", in the bibliography node of
jm-chicago-fullnote

**Comment by fbennett** [comment]
Nyrk, phones. "missing bit."

**Comment by demai** [comment]
Have you had time to look into this?

Frank Bennett <notifications@github.com> schrieb am Mi., 10. Apr. 2019,
14:41:

> I'll dig the documentation on it out of the old manual tomorrow and put it
> on ReadTheDocs. If I forget, feel free to ping me.
>
> The missing but was "exclude-types", in the bibliography node of
> jm-chicago-fullnote
>

**Comment by fbennett** [comment]
I got ready to copy the section across, and discovered [it's already in there](https://citeproc-js.readthedocs.io/en/latest/running.html#selective-output-with-makebibliography). So score one for foresight. :-)

**Comment by denismaier** [comment]
Hi,
there's been some [discussion](https://github.com/citation-style-language/documentation/issues/71) about this again and it seems this will not be implemented in CSL but it's expected to be a feature in the domain of calling applications.
Now, the idea is not to insert one subdivided bibliography but multiple selected bibliographies. Headings will be inserted by the user.
I guess this makes significantly easier. Citeproc-js should already be mostly able to do this, right? 
What do you think about this? What would be needed for this to work?

**Comment by fbennett** [comment]
Closing this, as the preferred solutions raised in the linked citation-style-language discussion would not impact processor code.
