### ISSUE TITLE
Ensure that citation.properties exists before accessing it

### ISSUE THREAD

**Issue by hubgit** [Juris-M/citeproc-js#106]
A [recent change](https://github.com/Juris-M/citeproc-js/commit/81f72a947ac64f96d19f8216e44be6fb93e844e4#diff-64dfc597299f19f1ec2866ede959bc88R185) added code that accesses `citation.properties.noteIndex`:

https://github.com/Juris-M/citeproc-js/blob/master/src/api_cite.js#L180-L194

However, this happens before the code ensuring that `citation.properties` is set:

https://github.com/Juris-M/citeproc-js/blob/master/src/api_cite.js#L251

This causes an error to be thrown when `citation` doesn't have a `properties` object.

I've worked around this by setting `properties: { noteIndex: 0 }` on all citations, but I think this is meant to be optional.

**Comment by fbennett** [comment]
Thanks for reporting. I'll add a check very soon.

**Comment by fbennett** [comment]
Should be fixed now by https://github.com/Juris-M/citeproc-js/commit/fb668187fe2271c0d06d27bcf8865dbe733f9ea6. Thanks for catching that.
