### ISSUE TITLE
citeproc_commonjs.js typeError

### ISSUE THREAD

**Issue by GrennanM** [Juris-M/citeproc-js#110]
I was getting a typeError thrown on line 14621:

`if (lst[i].replace(/^[a-z]\.\s+/, "").match(/[^\s0-9ivxlcmIVXLCM]/)) {`

The error was lst.[i].replace is not a function. 

Solved with:

`if (("" + lst[i]).replace(/^[a-z]\.\s+/, "").match(/[^\s0-9ivxlcmIVXLCM]/)) {`

Not sure if it's relevant to anyone else but thought I'd flag it anyway.

**Comment by fbennett** [comment]
Something numeric creeping in. Thanks for reporting this, will adopt your fix.

**Comment by GrennanM** [comment]
Happy I could help. Thanks for all your work on this project.

**Comment by fbennett** [comment]
Oops, missed this in the last couple of updates. Now fixed by https://github.com/Juris-M/citeproc-js/commit/7dbdc1917c7250df96fbd6972033cf9073944c14. Thanks for reporting the crash.
