### ISSUE TITLE
Citation incorrect when author and year are the same

### ISSUE THREAD

**Issue by coryschires** [Juris-M/citeproc-js#111]
:warning: I would like to have created a live example illustrating this problem. I tried using [this working demo](https://citeproc-js.readthedocs.io/en/latest/dynamic-editing.html) as a starting point. Unfortunately, the setup was rather involved and I couldn't get it working. I'd be sweet if there were a plunkr (or codepen or whatever) which we could use to quickly create live examples. Nevertheless, I've tried to leave a detailed write up, including all the supporting data, so maybe this can be added to your test suite?

Also: This issue is similar to https://github.com/Juris-M/citeproc-js/issues/86. But apparently that fix does not work here?

#### Setup
* Using citeproc.js version 2.1.239
* Using `chicago-author-date` CSL (although the same problem may exist for other citation styles?)

#### Article body text

    This should be citation A [@7960].

    And this should be citation B [@7961].

#### Citations (as CSL-JSON)

    [
      {
        "id": "7960",
        "page": "115-129",
        "type": "paper-conference",
        "title": "A model of bridge choice across the Mississippi River in Minneapolis",
        "author": [
          {
            "given": "C.",
            "family": "Carrion"
          },
          {
            "given": "D.",
            "family": "Levinson"
          }
        ],
        "issued": {
          "date-parts": [
            [
              2012
            ]
          ]
        },
        "publisher": "Springer",
        "container-title": " Network reliability in practice: Selected papers from the 4th International Symposium on Transport Network Reliability",
        "publisher-place": "New York, NY"
      },
      {
        "id": "7961",
        "page": "720-741",
        "type": "article-journal",
        "issue": "4",
        "title": "Value of reliability: A review of the current evidence",
        "author": [
          {
            "given": "C.",
            "family": "Carrion"
          },
          {
            "given": "D.",
            "family": "Levinson"
          }
        ],
        "issued": {
          "date-parts": [
            [
              2012
            ]
          ]
        },
        "volume": "46",
        "container-title": "Transportation Research Part A"
      }
    ]

## Problem
The in-text citations are not rendering as expected. Specifically, the appended letter (e.g. `a`) is not included.

Here's a screenshot from my application which illustrates the problem:

![Screen_Shot_2019-05-21_at_2_45_55_PM-2](https://user-images.githubusercontent.com/104563/58126309-4c9caf00-7bd8-11e9-83a7-dd8ba6909ebd.png)

**Comment by fbennett** [comment]
What method are you using to render the citations (processCitationCluster vs makeCitationCluster)?

**Comment by fbennett** [comment]
I would need more information on how you are running the processor to give an answer, but disambiguation of citations by year-suffix is extremely well tested and works reliably. I can only guess, but the most likely cause of what you are seeing (failure of the year suffix to appear on the first cite of a disambiguated pair set in two separate citations) is that you are using processCitationCluster to generate citations incrementally, and you are not updating the document or an output object with the full array of values returned by the second invocation of processCitationCluster.

**Comment by coryschires** [comment]
Thanks for the feedback. I will look into how we're using it and follow up.

**Comment by coryschires** [comment]
Ah tricky! I think I'm starting to understand the pitfall you're describing, and agree that this is likely a problem in my code.

Here's the relevant function from my implementation:

```js
_processCites() {
  const extractedCites = this._extractCiteFromMarkdown()
  let previousCites = []
  return extractedCites.map((cite) => {
    let citeObjectForCiteproc = {
      "citationID": cite.domId,
      "citationItems": cite.citationItems,
      "properties": {
        "noteIndex": 0 // Should always be 0
      }
    }
    let _result = this.citeproc.processCitationCluster(citeObjectForCiteproc, previousCites, [])
    let processedCitation = last(_result[1])
    let data = {
      rawMarkdown: cite.rawMarkdown,
      formattedText: processedCitation[1],
      position: processedCitation[0],
      citationItems: cite.citationItems,
      domId: processedCitation[2]
    }
    previousCites.push([data.domId, data.position])
    return data
  })
}
```

Sorry that this code is a bit hairy, but I think I see the problem... As you can see, I'm collecting and then looping through all the cites (e.g. `[@12345]`) in a markdown string. Then, for each cite, I am calling `processCitationCluster` passing that cite's data as well as all the data for each previous cite.

So, based on what you said, I am assuming that 

    Given I call processCitationCluster for cite 7960
      And it generates a cite string of "(Carrion and Levinson 2012)"
      But I'm expecting "2012a" – so that's wrong

    Next I call processCitationCluster for cite 7961
      And it generates a cite string of "(Carrion and Levinson 2012b)"
      Which is correct (because `processCitationCluster` now knows about 7960)

    But the cite for 7960 will never be updated to know about 7961
      Because that happened later in the loop
      So 7960 is stuck at "(Carrion and Levinson 2012)"
      But should be "(Carrion and Levinson 2012a)"

So assuming I got all that correct, how do I fix this bug? I'm assuming I am using `processCitationCluster` incorrectly? Or maybe I should be using an entirely different function?

Thanks again for helping me with this bug! This is tricky and your help has saved me tons of time already.

**Comment by fbennett** [comment]
This is very clear. You should see *my* code. :-)

The fix would begin with this block:
``` javascript
let processedCitation = last(_result[1])
    let data = {
      rawMarkdown: cite.rawMarkdown,
      formattedText: processedCitation[1],
      position: processedCitation[0],
      citationItems: cite.citationItems,
      domId: processedCitation[2]
    }
   ...
```
The `_result` from `processCitationCluster` is an array that includes revisions to past-rendered cites. It looks like you are reading off only one value from the array, for the current citation. A fix would involve tracking the `data` objects (outside this function), either by keying the objects to `position` or to `domid`, and updating `formattedText` in them (within this code block, iterating over remaining elements of the array).

**Comment by fbennett** [comment]
(If your writes to DOM are immediate, it looks like you could use `domid` to write the updated strings directly into the page.)

**Comment by coryschires** [comment]
Fixed based on your feedback! 

Thanks again for the help!

**Comment by fbennett** [comment]
My pleasure! This is for Scholastica?
