### ISSUE TITLE
CSL-M suggestion: bookinbook itemtype

### ISSUE THREAD

**Issue by denismaier** [Juris-M/citeproc-js#113]
Some style guides (Chicago, MLA) have the following requirement: Titles of originally independent works should be rendered in italics even if they are now republished in an anthology or in an edited book. Currently, this is not possible with Zotero/Jurism without using hackish solutions. The problem comes up in the Zotero forums from time to time, and I have the impression that there is some sort of consensus that this needs treatment in one way or another, but this would require an update to the CSL specs, and I don't know if this will happen next month or in two years.

What do you think about adding an item type like bookinbook to CSL-M as an interim solution? Another option would be a GUI switch like "Originally published as an independent work" (for items with item type chapter).

For references: https://forums.zotero.org/discussion/75154/

**Comment by fbennett** [comment]
I think that's covered by the recently added `alternative` and `alternative-text` elements in CSL-M.

https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#cs-alternative-extension

**Comment by denismaier** [comment]
Yes and no. While the translation/reprint-aspect is indeed covered by the new `alternative` elements I don't see how this solves the "title in italics" vs. "title in quotes" issue. Consider Adorno's *Negative Dialectics* as an example. Following the CMoS I would expect something along these lines.

```
Theodor W. Adorno, *Negative Dialektik*, in *Gesammelte Schriften*, by Theodor W. Adorno, ed. Rolf Tiedemann, vol. 6 (Frankfurt: Suhrkamp, 2003), 7–412.
```

Yet, with item type `chapter` we get:

```
Theodor W. Adorno, "Negative Dialektik," in *Gesammelte Schriften*, by Theodor W. Adorno, ed. Rolf Tiedemann, vol. 6 (Frankfurt: Suhrkamp, 2003), 7–412.
```

So, this is almost correct. The disturbing piece is that the title appears in quotes instead of being italicized. (As it is treated like any other chapter -- not taking into account that although this appears in a larger work this should be treated more than an independent book than a chapter.)

For these items using the alternative mechanism would be a) too much, and b) no solution to this specific problem.

**Comment by fbennett** [comment]
It would work just fine for your example. The main reference is to a book, so it is of book type (although with only title and author in the data in this case). The "in" join is supplied when two items are joined (i.e. when cs:alternative renders), and the rest is a normal book reference.

There would need to be some conditional jiggery-pokery to prevent "n.d." from rendering in the first reference, and maybe some other detail, but there will be burdens like that no matter what solution is adopted. The advantage is that the same mechanism can handle a variety of item-type combinations.

**Comment by denismaier** [comment]
Ok. I'll have a look.  (What are the conditions I could use to prevent "n.d."?)
That this can handle different kinds of item-type combinations sounds indeed awesome...

**Comment by fbennett** [comment]
Um ... I'll need to create a conditional for it. The test would need to check whether a language vector is set, and whether there are alt- variables on the item. If both are true, it would return true, if both are false, it will be false. I think that would be the only way to do it.

I have a bunch of things stacked up on short deadlines at the moment, and probably couldn't look at it until next week. But it's the concept that counts. :-/

**Comment by denismaier** [comment]
No worries, there's no need to hurry here.

Just for the record: A test using 日本社会学会 (author-date, Japanese) gave me this: 

```
Adorno, Theodor W., *Negative Dialektik*. Reprinted in: *Gesammelte Schriften*, 2003, Frankfurt: Suhrkamp.
```

Not so bad, but a simple "In" instead of "Reprinted in" would be better.

**Comment by denismaier** [comment]
Ok, "reprinted in" is defined (as a text element) just before the `alternative-text` is rendered. So no problem here.

For getting rid of "n.d.", I have now used a simple `<else-if variable="alt-issued"/>`. This works for this simple case, but I guess this will probably bite us in other cases. Also, are there cases where "n.d." would be legitimate?

**Comment by fbennett** [comment]
I suppose there might be cases in which "n.d." should be rendered in the first half of the citation. If an `alternative="true"` conditional is introduced, you could use it together with something like a test for `variable="publisher"` to constrain the suppression effect a bit.

**Comment by fbennett** [comment]
The revamp of parallel citations that I've put in place for legal support could be used to solve this problem more elegantly than either cs:alternative or cs:bookinbook, I think. It requires that users associate items that might be cited together via the Related tab in Jurism, but collapsing behavior can then be controlled quite precisely in the style, with minimal markup and without disturbing existing coding patterns.

I need to get the code for it into a Jurism beta release, and document the markup, which will take a week or so. No idea how it will be received, but I've just finished rebuilding the test suite items to make use of it, and I'm liking what I've seen so far.

**Comment by denismaier** [comment]
But doesn't this mean that users need to cite both items in a footnote?

**Comment by fbennett** [comment]
To produce the combined form, it would. But they would also be able to cite each independently, which might be useful depending on context. Seems more flexible.

**Comment by denismaier** [comment]
Yes, being able to cite each independently sounds great. I can think of some cases where this can be super useful... But in my example this might also entail disadvantages: if you use a fullnote style you must decided if a citation is the first item (where you need full publication details) or if it is a subsequent citation (where you only need author + shorttitle).

**Comment by fbennett** [comment]
I think is see what you mean. The book item "Gesammelte Schriften" that is the second cite of the pair would be in full-form on first reference, and in short form in subsequent references, even if cited with a different chapter partner. Is that incorrect, though?

**Comment by denismaier** [comment]
Well, there are quite a few cases where this might be appropriate, like when citing classical works that have been republished in multiple translations, anthologies; and you want to indicate which of those you are citing. 

In my case though I think this should be treated like any other chapter:
First: 
`Theodor W. Adorno, *Negative Dialektik*, in *Gesammelte Schriften*, by Theodor W. Adorno, ed. Rolf Tiedemann, vol. 6 (Frankfurt: Suhrkamp, 2003), 7–412.`

Subsequent:
`Adorno, *Negative Dialektik*.`

So, we omit information about the container in subsequent cites. Delegating this decision to the user would be somewhat unusual for a citation management tool.

If we think about what happens if we cite more items from the same container things might get more complicated though.

First:
`Theodor W. Adorno, *Minima Moralia*, in *Gesammelte Schriften*, by Theodor W. Adorno, ed. Rolf Tiedemann, vol. 4 (Frankfurt: Suhrkamp, 2003).` (providing full information again for the book item)

Alternative first:
`Theodor W. Adorno, *Minima Moralia*, in *Gesammelte Schriften*, vol. 4.` (using the short form for the book item)

Subsequent:
`Adorno, *Minima Moralia*.`

Anyway, usually I would not include information about the book item in subsequent cites.

**Comment by fbennett** [comment]
Got it, thanks. This would indeed not be a good solution for that case.

**Comment by bwiernik** [comment]
Couldn't this be addressed more simply by writing the style assuming that `book` items might have a `container-title` and then writing the title/container-title formatting macros accordingly? This is what apa.csl does for example.

**Comment by denismaier** [comment]
Yes, that could be a feasible approach. I see some requirements:

1. This should be handled consistently across styles. At the moment it does not work out of the box for Chicago or for MLA. For Chicago see my comments [here](https://forums.zotero.org/discussion/comment/336843/#Comment_336843), the MLA csl style uses the absence of `container-title` as a condition for using italics for the title.
2. Users should know that this is the preferred way to handle such items.
3. What happens with other fields in these cases? (For example `editor`: Is this the editor of the container or of the contained item?

I guess, we'd have to seriously play this through. In already complex styles like Chicago, this will lead to an even higher level of complexity, and it might well be that a new item type could be a simpler solution. But that's perhaps a discussion for the discourse forum...

**Comment by fbennett** [comment]
A useful discussion, but closing the issue pending separate discussion of one or more of the possibilities raised.

**Comment by bwiernik** [comment]
(We resolved this by adopting my proposal--accepting that `book` items might have à `container-title`)
