### ISSUE TITLE
CSL-M: Locale condition in choose elements not consistent with other conditions

### ISSUE THREAD

**Issue by denismaier** [Juris-M/citeproc-js#118]
I have the impression that the ìf locale` condition is not consistent with other conditions:

Case 1:
```
<if variable="title">
...
</if>
```
=> This checks whether the variable `title` is present and processes the element content if the variable is there.

Case 2:
```
<if locale="en">
...
</if>
```
=> This checks whether the locale is `en`. If yes, it processes the element content AND applies the locale "en" the terms, labels, etc.

So, while normal conditions perform one operation, `locale`-conditions seem to perform two operations in one step. This behaviour might be problematic in some cases. For example, if we want to change some element depending on locales, but without actually applying those locales to terms, labels, etc.

**Comment by fbennett** [comment]
If things are working as intended, the condition will accept multiple locales, evaluate `true` if any of them match, and apply the first-listed locale terms. That logic needs to be stated more clearly in [the documentation](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#locale-extension), but I think that will cover the case?

**Comment by denismaier** [comment]
Oh, it applies the first locale? That wasn't clear to me. (I've thought it'll apply all found locales.) That is much better than what I've expected, as long as we don't want to check for locales without actually changing the output locale... (I am not sure if this is a realistic scenario, but anyway.)
