### ISSUE TITLE
What is the expected behavior for title-case / sentence-case?

### ISSUE THREAD

**Issue by coryschires** [Juris-M/citeproc-js#119]
After [reviewing](https://github.com/Juris-M/citeproc-js/issues/42) [several](https://github.com/Juris-M/citeproc-js/issues/78) [different](https://github.com/Juris-M/citeproc-js/issues/32) [issues](https://github.com/Juris-M/citeproc-js/issues/27), I still can't figure out how capitalization is intended to work. First, I understand this is an inherently complicated problem made worse by needless variation between citation styles.

Nevertheless, I can see (by reviewing issues) that Citeproc.js definitely attempts to enforce capitalization rules in at least in some cases. Furthermore, my own quick testing reveals that capitalization is enforced for some citation styles but not others:

* chicago-author-date
  - `title` – automatically converted to title-case
  - `container-title` – automatically converted to title-case
* APA
  - `title` – rendered literally (i.e. no automatic capitalization)
  - `container-title` – automatically converted to title-case
* MLA
  - `title` – automatically converted to title-case
  - `container-title` – automatically converted to title-case
* AMA
  - `title` – rendered literally (i.e. no automatic capitalization)
  - `container-title` – rendered literally (i.e. no automatic capitalization)

So my questions are:

* Why are some styles (e.g. chicago-author-date) automatically sentence-cased whereas other styles (e.g. AMA) are rendered literally?
* Why not automatically title-case `title` and `container-title` for all CSLs? I'm assuming there's a reason this is a bad idea?

Overall, I am trying to decide if I should throw some custom code at this problem or if it is best to rely on Citeproc.js (because y'all have thought this out and have already established the best possible behavior).

Thanks!

**Comment by fbennett** [comment]
Questions about the composition of styles would be for the CSL group. Their list is here:

https://discourse.citationstyles.org/

If there are bugs in the transforms, I can look into it, given test or test items that expose the fault.

**Comment by coryschires** [comment]
Thanks, That makes sense. In that case, I have a specific question.

According to [this blog post about APA styles](https://blog.apastyle.org/apastyle/2012/03/title-case-and-sentence-case-capitalization-in-apa-style.html), titles in references should be title-cased. Assuming that is correct, Citeproc.js does not appear to follow this rule. In my local testing, in APA, the `title` is rendered literally. I would expect it to be title-cased by Citeproc.

(I'm assuming I am misunderstanding something?)

**Comment by fbennett** [comment]
The page linked under "when they appear in the text of the paper" provides illustrations:

https://blog.apastyle.org/apastyle/2012/03/how-to-capitalize-and-format-reference-titles-in-apa-style.html

In references, APA uses sentence case. If the title of a work is written into the text of a document (not as a reference, but as a proper noun in running text), it get title case. The latter is not a citation.

**Comment by coryschires** [comment]
Ah. You are correct. Thank you for clarifying and sorry to have bothered you with this issue.
