### ISSUE TITLE
title-main / title-sub ignore language settings for title-casing

### ISSUE THREAD

**Issue by denismaier** [Juris-M/citeproc-js#120]
I have had just a quick look into the new main/sub-title-split-mechanism. Looks really good so far. Finally there's a way to change the punctuation between title and subtitle!

There seems to be one oddity though. `Title-main` and `title-sub` seem to force title case also when a language other than English is set. 

If we use this
```
<group delimiter=" vs. ">
        <group delimiter=": ">
            <text variable="title-main" text-case="title" font-style="italic"/>
            <text variable="title-sub" text-case="title" font-style="italic"/>
        </group>
        <text variable="title" text-case="title" font-style="italic"/>
</group>
```

with a German title (e.g. "Ein wichtiges Buch: Mit einem interessanten Untertitel"), we expect: 

```
*Ein wichtiges Buch: Mit einem interessanten Untertitel* vs. *Ein wichtiges Buch: mit einem interessanten Untertitel*
```

But the result is:
```
*Ein Wichtiges Buch: Mit Einem Interessanten Untertitel* vs. *Ein wichtiges Buch: Mit einem interessanten Untertitel*
```

**Comment by fbennett** [comment]
I'll check up on forced title-casing. That certainly isn't right if it's happening. I also undertook to turn the toggle on in the Jurism beta that I released today, then forgot. It will be enabled in the next one to go up, though.

**Comment by denismaier** [comment]
Well, I have actually tested this with the current Juris-M beta. Splitting
seems to work nevertheless, inappropriate title-casing aside.

By the way, what does this splitting mean for language variants? Title-main
[title-main-transliteration]: title-sub [title-sub-transliteration]?
Wouldn't be ideal, right?

Frank Bennett <notifications@github.com> schrieb am Mi., 21. Aug. 2019,
12:56:

**Comment by denismaier** [comment]
Oh, and are you sure the toogle isn't on? 

This here: 

```
<group delimiter=": ">
  <text variable="title-main" text-case="title" font-style="italic"/>
  <text variable="title-sub" text-case="title" font-style="italic"/>
</group>
```

renders nothing in vanilla Zotero, but it works with the current Juris-M beta.

**Comment by fbennett** [comment]
Oh! Must be my quick look at the code was a little too casual. I will look
at this more carefully over the next couple of days, after I clear some
basic documentation for jurisdiction editing in the latest beta release.

**Comment by denismaier** [comment]
Hey Frank, any news here?

**Comment by fbennett** [comment]
Still need to deal with it, sorry. It's rising in the queue, should get
there soon.

**Comment by denismaier** [comment]
Ping. Amy News?

**Comment by denismaier** [comment]
Ping again...

**Comment by fbennett** [comment]
The failure of the language condition on text-case has been fixed in release 1.2.31. It will have the unfortunate side-effect that you note (Main Title [Main title variant]: Subtitle [Subtitle variant]). That's a tough one to address, and I'm not quite sure yet how to resolve it. Some special handling of a specifically named macro might work, folding that into the existing code would involve workarounds. It needs some thought. Suggestions on how to minimize the complexity of a solution in the hands of style authors very welcome!

**Comment by denismaier** [comment]
> That's a tough one to address, and I'm not quite sure yet how to resolve it. [...] Suggestions on how to minimize the complexity of a solution in the hands of style authors very welcome!

What if you extend the mechanism a bit:
Currently, we have to use `title-main` and `title-sub` explicitly. What if you add an implicit mechanism that just replaces the full `title` with `title-main` + custom separator + `title-sub`. Then style authors can just call the full `title` (with the full variant), `title-main` (with its variant) or `title-sub` (with its variant). For the separator an inheritable attribute like `title-sub-separator` would be quite handy (was suggested by @georgd [here](https://discourse.citationstyles.org/t/handling-main-sub-title-splits-citeproc-js/1563/14?u=denis_maier).

**Comment by denismaier** [comment]
I'll close this one and open a new issue, since the original problem was solved. (Thanks, again!)
