### ISSUE TITLE
Implicit setting of title-short produces bad legal_case short-form citations.

### ISSUE THREAD

**Issue by dchawisher** [Juris-M/citeproc-js#123]
As I understand it, citeproc-js implicitly sets title-short when title-short is empty. Something to do with getting titles and subtitles to work properly. The downside of this is that documents of the type legal_case do not produce correct near-note citations in the US citation module.

In the module, for legal_case citations after the first, there is a conditional choosing between "title" and "title-short" based on whether "title-short" exists. That conditional does not work properly, which I think is because citeproc-jc implicitly sets title-short. 

If title="John v. Smith", title-short="", and position="near-note", the expected output is "John v. Smith". Instead, the output is "John v".

**Comment by fbennett** [comment]
Whoa, thanks for flagging this. A Jurism update is on the horizon, I'll be sure this is fixed in a processor and pulled in before it goes live.
