### ISSUE TITLE
`label` for non-numeric variables

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#124]
I have the following case:
```
<group delimiter=": ">
  <text variable="title"/>
  <!-- Replace with volume-title as that becomes available -->
  <choose>
    <if is-numeric="volume" match="none">
      <group delimiter=" ">
        <label variable="volume" form="short" text-case="capitalize-first"/>
        <text variable="volume"/>
      </group>
    </if>
  </choose>
</group>
```

Output is correct for this item:
```
[
  {"id":"Titlea","type":"book","title":"Title","volume":"1. Volume title"}
]
```
Expected: Title: Vol. 1. Volume title
Observed: Title: Vol. 1. Volume title

If the non-numeric `volume` resembles a list, however, citeproc-js interprets it as being plural:
```
[
  {"id":"Titlea","type":"book","title":"Title","volume":"1. Volume title, second, and third"}
]
```
Expected: Title: Vol. 1. Volume title, second, and third.
Observed: Title: Vols. 1. Volume title, second, and third.

While it is possible that `volume` might contain a list of several non-numeric volume labels, I suspect much more often, non-numeric volume items would be something like this:
Travis, C. B., White, J. W., Rutherford, A., Williams, W. S., Cook, S. L., & Wyche, K. F. (Eds.). (2018). `APA handbook of the psychology of women: Vol. 1. History, theory, and battlegrounds`. American Psychological Association. https://doi.org/10.1037/0000059-000

I suggest that `label` always return `single` values when the `variable` is non-numeric.

@adam3smith @rmzelle what do you think?

**Comment by bwiernik** [comment]
@adam3smith @fbennett Do you think we could resolve this? I think that for the purposes of `label`, non-numeric variables should always be considered singular.

**Comment by fbennett** [comment]
I've made this change just now, in `citeproc-js` release tag 1.2.35, along with a couple of other improvements to numeric handling. No impact on existing tests, it should be safe to deploy.

**Comment by adam3smith** [comment]
yeah, this is a sensible change, thanks. One of our hopes for the specs is to clarify more such decisions there -- is this a candidate?

**Comment by bwiernik** [comment]
Thanks Frank!

**Comment by bwiernik** [comment]
@fbennett Can you point me to the parsing code in citeproc-js for this so I can add it to the spec?
