### ISSUE TITLE
Empty sortedItems array causes error in CSL.Engine.processCitationCluster 

### ISSUE THREAD

**Issue by hubgit** [Juris-M/citeproc-js#127]
Under certain conditions an error is thrown in the `processCitationCluster` method:

> TypeError: Cannot read property '1' of undefined at CSL.Engine.processCitationCluster 

The relevant line in `citeproc_commonjs.js` is `oldlastid =  citations[j - old_last_id_offset].sortedItems.slice(-1)[0][1].id`

The error is thrown because the `sortedItems` array is empty.

The conditions are:

* `apa.csl` style (but not `peerj.csl`, for example, which also uses author-year labels)
* a citation with an empty `citationItems` array
* followed by a citation with a non-empty `citationItems` array and mode set to `author-only`

Code to reproduce the error can be found here: https://codesandbox.io/s/epic-kilby-p9u5m

**Comment by fbennett** [comment]
What is the use case for registering a citation with no items? That may throw errors in numerous places, and the immediate thought would be that it should throw a blocking error at the top of the function.

**Comment by hubgit** [comment]
> What is the use case for registering a citation with no items?

In this particular case it's an editor where authors can add and remove items from a citation, which means that sometimes a citation can contain no items.

It would be possible, with a small amount of extra complexity, to work around this error by skipping citations with no items and setting their label to an empty string, although it's been working with no problems so far, apart from this specific case.

**Comment by fbennett** [comment]
I've wrapped the operation that crashed in a conditional, and it will clear that operation now. The processor will return "[NO_PRINTED_FORM]" as the citation text when `citationItems` is empty.

**Comment by hubgit** [comment]
Wonderful, thanks @fbennett.
