### ISSUE TITLE
Convention to specify a link for bibliography

### ISSUE THREAD

**Issue by howthebodyworks** [Juris-M/citeproc-js#128]
Currently AFAICT [CSL is in limbo regardingspecification for hyperlinks in bibliographies](https://github.com/citation-style-language/schema/issues/145) and so CSL implementers must invent their own convention for specifying hyperlinks. Is this something we are interested in? Do we need some way of specifying that part or all of a bibliographical entry (such as the whole entry, or the title, or the author name/date or something) should be a hyperlink (either to the `URL` field or the `DOI` link)? Currently it seems there is the `wrap_url_and_doi` process which can be ugly, although of course one can make it look nicer with CSS for HTML output. if one has control of the CSS. There are also [macro hacks](https://github.com/jgm/pandoc-citeproc/issues/318) for LaTeX output; but it seems like some kind of unified approach mgiht be in order?

**Comment by howthebodyworks** [comment]
For bonus points we could try to stay in step with `pandoc-citeproc` where I also opened [a ticket](https://github.com/jgm/pandoc-citeproc/issues/432) about this, that being the other citeproc system that I personally use :wink:

**Comment by fbennett** [comment]
Work is proceeding on a next-generation CSL implementation for use with JavaScript at https://github.com/cormacrelf/citeproc-rs, with support from Zotero. While that work proceeds, it is probably best not to inject an implementation-specific solution into citeproc-js. The best fora for discussion would be the `citeproc-rs` tracker, and the CSL discussion boards (https://discourse.citationstyles.org/).
