### ISSUE TITLE
Help: We need to pass in non standard fields to Citeproc, with a modified CSL

### ISSUE THREAD

**Issue by vhcoder** [Juris-M/citeproc-js#129]
We are building a product in which we have to generate citations for research efforts, but in addition, add more fields that are specific to the application. For example, Description of Effort. 

We were going to add these variables to a macro, which would be then pulled into the CSL.  But-- this would fail validation as those variable names are unknown to the citeproc processor which uses a built-in variables directory which is [here](https://github.com/Juris-M/schema/blob/b1c2dc88a5956918d225adc2b88a17e9db3e3a88/csl-variables.rnc).

Question---is there a way to pass in both a custom .rnc file and custom CSL along with the data comporting to the custom CSL to citeproc for it to format it correctly?

We did look at the [cheater syntax] (https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cheater-syntax-for-odd-fields)

But, we wanted something that we could use outside of note fields. 

Thanks!

**Comment by fbennett** [comment]
The processor does not perform validation, so it will process whatever you throw at it. It does carry internal lists of [numeric](https://github.com/Juris-M/citeproc-js/blob/3389e9b23a1873c1bb0af16eef7533aefd669701/src/load.js#L613), [name](https://github.com/Juris-M/citeproc-js/blob/3389e9b23a1873c1bb0af16eef7533aefd669701/src/load.js#L581), and [date](https://github.com/Juris-M/citeproc-js/blob/3389e9b23a1873c1bb0af16eef7533aefd669701/src/load.js#L638) variables, but other variables in the input object will be treated as ordinary text variables that can be rendered via a `cs:text` node. So as far as the processor is concerned, if all you need are additional text variables, you should be able to just do it.

Style validation is a separate problem. If you want to validate styles that use non-CSL variables, you can either patch the CSL `rnc` grammar itself, or supplement it with a patch file during processing. For guidance on that, the [CSL Discourse](https://discourse.citationstyles.org/) list would be the best forum---I've patched the grammar for CSL-M extensions to the language recognized by the processor, but my knowledge about how the patching mechanism works is pretty thin.

**Comment by vhcoder** [comment]
Thank you, that was helpful. We will probably end up patching the `rnc` grammar as well. But will probably throw the question in the discourse list first. Thank you for the help, and a great product!
