### ISSUE TITLE
New Condition [CSL-M): Check if variables are equal

### ISSUE THREAD

**Issue by denismaier** [Juris-M/citeproc-js#130]
Would it be possible to add a new condition to `citeproc-js` that checks if two variables are equal.

```
<choose>
<if equal="author bookauthor">
...
</if>
</choose>
```

That would be a CSL-M addition, of course, as this is not part of the current CSL specs. How complicated would that be?

**Comment by denismaier** [comment]
What do you think?

**Comment by fbennett** [comment]
I see there is discussion of equivalence testing in the CSL forum. Will wait for the outcome of that in test fixtures.
