### ISSUE TITLE
Composite displays locator double

### ISSUE THREAD

**Issue by svenhanssen** [Juris-M/citeproc-js#131]
I think I have found a bug with the "composite" mode in "processCitationCluster". For example, if you try to generate a citation in composite mode and in the [APA 6th edition style](https://github.com/citation-style-language/styles/blob/master/apa-6th-edition.csl), it generates the following:

> Hanssen, p. (2006, p.57)

It should be this:

> Hanssen (2006, p. 57)

Is there a way to solve this?

**Comment by svenhanssen** [comment]
@fbennett Do you know if there is any progress in this? Do I maybe need to provide more information?

**Comment by fbennett** [comment]
Dear Sven,

Sorry, I had missed this. Will check it out today and post again if I have
trouble reproducing the fault.

FB

**Comment by fbennett** [comment]
Thanks for following up, I wasn't paying attention.
This is fixed in tagged release 1.4.6.
