### ISSUE TITLE
page abbreviation fails when data delimited by en dash

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#136]
If I separate pages in the `pages` field by an en dash, rather than a hyphen, pages are not correctly abbreviated (e.g., in Chicago (full note)). 

Data:
```
[
  {"id":"Kalnay1996NCEPNCAR","accessed":{"date-parts":[[2019,10,17]]},"author":[{"family":"Kalnay","given":"E."},{"family":"Kanamitsu","given":"M."},{"family":"Kistler","given":"R."},{"family":"Collins","given":"W."},{"family":"Deaven","given":"D."},{"family":"Gandin","given":"L."},{"family":"Iredell","given":"M."},{"family":"Saha","given":"S."},{"family":"White","given":"G."},{"family":"Woollen","given":"J."},{"family":"Zhu","given":"Y."},{"family":"Chelliah","given":"M."},{"family":"Ebisuzaki","given":"W."},{"family":"Higgins","given":"W."},{"family":"Janowiak","given":"J."},{"family":"Mo","given":"K. C."},{"family":"Ropelewski","given":"C."},{"family":"Wang","given":"J."},{"family":"Leetmaa","given":"A."},{"family":"Reynolds","given":"R."},{"family":"Jenne","given":"Roy"},{"family":"Joseph","given":"Dennis"}],"container-title":"Bulletin of the American Meteorological Society","container-title-short":"Bull. Amer. Meteor. Soc.","DOI":"10/fg6rf9","ISSN":"0003-0007","issue":"3","issued":{"date-parts":[[1996,3]]},"page":"437–472","source":"journals.ametsoc.org (Atypon)","title":"The NCEP/NCAR 40-year reanalysis project","type":"article-journal","URL":"https://journals.ametsoc.org/doi/abs/10.1175/1520-0477%281996%29077%3C0437%3ATNYRP%3E2.0.CO%3B2","volume":"77"}
]
```

Current output:
<div class="csl-bib-body" style="line-height: 1.35; margin-left: 2em; text-indent:-2em;">
  <div class="csl-entry">Kalnay, E., M. Kanamitsu, R. Kistler, W. Collins, D. Deaven, L. Gandin, M. Iredell, et al. “The NCEP/NCAR 40-Year Reanalysis Project.” <i>Bulletin of the American Meteorological Society</i> 77, no. 3 (March 1996): 437–472. <a href="https://doi.org/10/fg6rf9">https://doi.org/10/fg6rf9</a>.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=info%3Adoi%2F10%2Ffg6rf9&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=The%20NCEP%2FNCAR%2040-year%20reanalysis%20project&amp;rft.jtitle=Bulletin%20of%20the%20American%20Meteorological%20Society&amp;rft.stitle=Bull.%20Amer.%20Meteor.%20Soc.&amp;rft.volume=77&amp;rft.issue=3&amp;rft.aufirst=E.&amp;rft.aulast=Kalnay&amp;rft.au=E.%20Kalnay&amp;rft.au=M.%20Kanamitsu&amp;rft.au=R.%20Kistler&amp;rft.au=W.%20Collins&amp;rft.au=D.%20Deaven&amp;rft.au=L.%20Gandin&amp;rft.au=M.%20Iredell&amp;rft.au=S.%20Saha&amp;rft.au=G.%20White&amp;rft.au=J.%20Woollen&amp;rft.au=Y.%20Zhu&amp;rft.au=M.%20Chelliah&amp;rft.au=W.%20Ebisuzaki&amp;rft.au=W.%20Higgins&amp;rft.au=J.%20Janowiak&amp;rft.au=K.%20C.%20Mo&amp;rft.au=C.%20Ropelewski&amp;rft.au=J.%20Wang&amp;rft.au=A.%20Leetmaa&amp;rft.au=R.%20Reynolds&amp;rft.au=Roy%20Jenne&amp;rft.au=Dennis%20Joseph&amp;rft.date=1996-03&amp;rft.pages=437%E2%80%93472&amp;rft.spage=437&amp;rft.epage=472&amp;rft.issn=0003-0007"></span>
</div>

<br><br>

Expected output:
<div class="csl-bib-body" style="line-height: 1.35; margin-left: 2em; text-indent:-2em;">
  <div class="csl-entry">Kalnay, E., M. Kanamitsu, R. Kistler, W. Collins, D. Deaven, L. Gandin, M. Iredell, et al. “The NCEP/NCAR 40-Year Reanalysis Project.” <i>Bulletin of the American Meteorological Society</i> 77, no. 3 (March 1996): 437–72. <a href="https://doi.org/10/fg6rf9">https://doi.org/10/fg6rf9</a>.</div>
  <span class="Z3988" title="url_ver=Z39.88-2004&amp;ctx_ver=Z39.88-2004&amp;rfr_id=info%3Asid%2Fzotero.org%3A2&amp;rft_id=info%3Adoi%2F10%2Ffg6rf9&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&amp;rft.genre=article&amp;rft.atitle=The%20NCEP%2FNCAR%2040-year%20reanalysis%20project&amp;rft.jtitle=Bulletin%20of%20the%20American%20Meteorological%20Society&amp;rft.stitle=Bull.%20Amer.%20Meteor.%20Soc.&amp;rft.volume=77&amp;rft.issue=3&amp;rft.aufirst=E.&amp;rft.aulast=Kalnay&amp;rft.au=E.%20Kalnay&amp;rft.au=M.%20Kanamitsu&amp;rft.au=R.%20Kistler&amp;rft.au=W.%20Collins&amp;rft.au=D.%20Deaven&amp;rft.au=L.%20Gandin&amp;rft.au=M.%20Iredell&amp;rft.au=S.%20Saha&amp;rft.au=G.%20White&amp;rft.au=J.%20Woollen&amp;rft.au=Y.%20Zhu&amp;rft.au=M.%20Chelliah&amp;rft.au=W.%20Ebisuzaki&amp;rft.au=W.%20Higgins&amp;rft.au=J.%20Janowiak&amp;rft.au=K.%20C.%20Mo&amp;rft.au=C.%20Ropelewski&amp;rft.au=J.%20Wang&amp;rft.au=A.%20Leetmaa&amp;rft.au=R.%20Reynolds&amp;rft.au=Roy%20Jenne&amp;rft.au=Dennis%20Joseph&amp;rft.date=1996-03&amp;rft.pages=437%E2%80%93472&amp;rft.spage=437&amp;rft.epage=472&amp;rft.issn=0003-0007"></span>
</div>

**Comment by fbennett** [comment]
Fixed in processor tag 1.4.50
