### ISSUE TITLE
annote-short not recognized from note

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#137]
Per this line: https://github.com/Juris-M/citeproc-js/blob/3389e9b23a1873c1bb0af16eef7533aefd669701/src/node_text.js#L258

Using this style:
https://gist.githubusercontent.com/bwiernik/1142159e74c104fcb1bd119058fcf924/raw/ab9127d54eb0d0d8353b9a5a5226ec0f2ecd72e2/apa-fullnote-annotations.csl

With this item data:
```
[
  {"id":"TestPatent","note":"annote: First annotation\nannote-short: Second annotation","title":"test patent","type":"patent"}
]
```

I expect the first note in a document to yield:
`First annotation`

And the second note to yield:
`Second annotation`

However, all notes instead yield `First annotation`. The short form is never picked up. Perhaps it has to do with this line? https://github.com/Juris-M/citeproc-js/blob/185db18d0cbc69dd0fca43d96ef42149fc76e349/src/util_transform.js#L212

**Comment by fbennett** [comment]
That's probably it. Why would you want to set a short form for an annotation? It seems like that could be confusing.

**Comment by bwiernik** [comment]
A user was looking to use it for first versus subsequent labels for an item (I believe they were using ‘patent’ to hold freeform notes that they referred back to by a short name later)

**Comment by fbennett** [comment]
From the CSL of the style, the user is writing the entire text of the citation into the variable in a fixed form. That's really bad practice. Are you sure you want to encourage it?

**Comment by bwiernik** [comment]
Shrugs. It’s for an internal report style at an agency. These are technical footnotes.

**Comment by fbennett** [comment]
I'm ... not sure what I've said on it in the past, but ... in this instance, at least, the user's case in this instance for extending "-short" to cover every possible variable on an item is pretty weak. If they are putting the entire content of the reference in a single field of the patent type, they could just write the short form in another arbitrary field (or as `title-short`), and solve the problem that way.

**Comment by bwiernik** [comment]
My understanding from our previous discussions was that any CSL variable could be provided a short form with `*-short`, but appears to have only been applied to title variables.

**Comment by fbennett** [comment]
I thought I might have said something like that. Isn't `title-short` a good fit for the subsequent reference in this case, though? Other styles would use that in a short-form back-reference, and relying on it would at least encourage some effort to keep the `title` field aligned with whatever is written into `annote`.

**Comment by bwiernik** [comment]
Okay, I'll suggest this user using title-short or citation-label or similar.
