### ISSUE TITLE
limit-day-ordinals-to-day-1 with date ranges

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#139]
https://forums.zotero.org/discussion/83874/date-ranges-with-ordinal-french-option-format#latest

Current citeproc-js behavior of `limit-day-ordinals-to-day-1="true"` isn't correct with date ranges. If the first day in a range is "1", then the ordinal is applied to both dates. If the first day is not "1", then the ordinal is applied to neither date.

`Event Date: 2011-07-01/2011-07-14` -> « 1ᵉʳ-14ᵉ juill. 2011 » (the outcome should be : 1ᵉʳ-14 juill. 2011)
`Event Date: 2011-07-14/2011-07-01 -> « 14-1 juill. 2011 » (the outcome should be : 14-1ᵉʳ)

Can this be fixed?

Here is a test:
https://gist.github.com/bwiernik/a18438c70e7a98155812a6652ffa91cc

**Comment by fbennett** [comment]
Thanks so much for the test, it makes things *so* much easier. I've fixed the bug, and a revision to the processor will be up shortly.
