### ISSUE TITLE
delimiter-precedes-last="after-inverted-name"

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#143]
The behavior for `delimiter-precedes-last="after-inverted-name"` doesn't seem correct. There are two problems:

1. It's adding the delimiter, even if the the name is literal, so it's not inverted (first item beow),
1. It isn't adding the delimiter when there are more than two authors, even if the names are inverted

I'm expecting:
<div class="csl-bib-body">
  <div class="csl-entry">Australian Government Productivity Commission & New Zealand Productivity Commission</div>
  <div class="csl-entry">Weinstock, R., Leong, G. B., & Silva, J. A.</div>
</div><br>

But I'm getting:<br>
<div class="csl-bib-body">
  <div class="csl-entry">Australian Government Productivity Commission, & New Zealand Productivity Commission</div>
  <div class="csl-entry">Weinstock, R., Leong, G. B. & Silva, J. A.</div>
</div>
<br>

Test:
https://gist.github.com/bwiernik/ee972bf339867219df3c8546f32c4f3a

**Comment by fbennett** [comment]
Thanks for the report. This is fully broken. Resolving it will take some time. The processing flow has quite a few layers, and it's not obvious where changes will need to be made. I'll be expanding the test to cover two additional inputs: [invert-name] + [institution] and [institution] + [invert-name], and poke away at it as time permits.

**Comment by bwiernik** [comment]
Thanks.

**Comment by fbennett** [comment]
This should be fixed in the latest release (citeproc-js 1.4.13).
