### ISSUE TITLE
README out-of-sync with 'Getting started'

### ISSUE THREAD

**Issue by sanmai-NL** [Juris-M/citeproc-js#145]
https://github.com/Juris-M/citeproc-js/blob/49a9088e494a3e7d214e1a124a58b6b884ce5fc2/README.rst
mentions `cslrun` whereas
https://github.com/Juris-M/citeproc-js-docs/blob/827f4bd6ce2dc6aa24f59eb49930f5962047b456/setting-up.rst
mentions a different command.

**Comment by fbennett** [comment]
Thanks! Fixed.
