### ISSUE TITLE
For legal cases, need a way to prevent suppression of year following use of year-as-volume (aka "collection number") field

### ISSUE THREAD

**Issue by dchawisher** [Juris-M/citeproc-js#146]
In certain circumstances, cireproc-js suppresses the `issued` date field for `legal_case` citations. This happens when all of the following are true:

1. The `collection-number` field is present.
2. The `issued` field is displayed with `date-parts="year"`.
3. The `collection-number` field is the same as the year portion of the `issued` field.

I understand that this is intentional and that it is necessary to properly render some citation styles. I would still request that the functionality be changed to include a style-level or module-level off-switch, for two reasons.

1. For my use case, disabling this suppression is essential. I am creating a style and style module for use in litigation. For many of the same reasons that Juris-M is useful for legal academics, it is also useful for writing briefs. The common practice in litigation is to entirely ignore certain citation rules because they take up valuable space. For example, rather than include the full date of an opinion in an archive like Westlaw or Lexis, litigators generally include just the year. This should result in a citation like _Joe v. Jim_, 2020 WL 12345 (N.Y. 2020). Because of the year suppression feature, what I get is _Joe v. Jim_, 2020 WL 12345 (N.Y.).
2. The date suppression doesn't work entirely right, so it should probably be revisited anyway. If the citation module calls for a date with `year-month-day` or `year-month`, but the field in question only has a year, the year will not be suppressed. So it is possible to render a citation like _Joe v. Jim_, 2020 WL 12345 (N.Y. 2020)—you simply have to tell the style module to render year-month-day but only give it a year.

Sorry for the length of this explanation, and thanks for considering it.

**Comment by fbennett** [comment]
Thanks for this. We can add a style option to disable suppression. Something like `disable-duplicate-year-suppression="us"`, binding the disable to jurisdiction, would allow Canadian cites to render correctly in the same document. Limiting suppression on the basis of `date-parts` is probably appropriate, and with the other change, there wouldn't be temptation to use it as a workaround. Would that work?

**Comment by dchawisher** [comment]
That would be perfect. Thank you.

**Comment by fbennett** [comment]
This is in the processor master now, and will appear at the next release (which might take some time---now clearing a bunch of interrelated issues for Austria and Germany).
code: https://github.com/Juris-M/citeproc-js/commit/f52ac8e7b86cf2b0bb6cf0529ac472e8bdbc39cf
test: https://github.com/Juris-M/citeproc-js/commit/6b1c3c8d067f526a402eb092bfc7eb28409a1771
