### ISSUE TITLE
Parallel citations limited to two items

### ISSUE THREAD

**Issue by georgd** [Juris-M/citeproc-js#150]
@fbennett please, could you have a look at this? Since yesterday, my parallel citation tests only render two citations as parallel, the third is treated as a non-parallel citation. This happens in citations and bibliographies likewise. Maybe, the changes necessary for `@no-repeat` broke something?

**Comment by fbennett** [comment]
Seems to work fine in a basic configuration. https://github.com/Juris-M/citeproc-js/commit/8758d26d41247ed916f208349be38ee6c51250e7 The first thing to check would be the validity of the style code (the test runner doesn't validate style modules, unfortunately), then if the error persists, reducing to a minimum of CSL code to reproduce.

**Comment by georgd** [comment]
Found the cause. I changed the item IDs to the original ids from the Zotero db so cslrun -U wouldn’t add the same items again (before, I had them as `ITEM-1`, `ITEM-2`, `ITEM-3`). But I forgot to change them in the seeAlso-section... 

I’m very sorry for the agitation. I hope, it didn’t cost you too much time.

**Comment by fbennett** [comment]
No problem at all! With the recent adjustments to features, bug vigilance is always to the good.
