### ISSUE TITLE
Call jurisdiction country code in csl file

### ISSUE THREAD

**Issue by georgd** [Juris-M/citeproc-js#161]
Is there a way to call the country code of a jurisdiction in a style file? The IBFD requires legal sources to be prefixed with the country code of the jurisdiction. Currently, I’m testing for each jurisdiction and return the corresponding code as can be seen in https://github.com/georgd/jm-styles/blob/304816a81b7126074ec62137e3145025a5ab77c5/jm-ibfd-with-page-label.csl#L62-L66 ...

This could be fine, but then it won’t work with sub-jurisdictions. E.g. an item with `"jurisdiction": "at:innsbruck:feldkirch"` won’t return true when testing for `at`. This is fine in principle, as `at` is a jurisdiction in its own right. (Perhaps something like a starred test could be introduced like `<if jurisdiction="at*">` to test for jurisdiction `at` and any sub-jurisdiction?)

**Comment by fbennett** [comment]
Yes! Just use this:
```
<text variable="jurisdiction" form="short"/>
```

**Comment by georgd** [comment]
Two issues arise here: 

- like above, sub-jurisdictions are getting in the way: while for all, say, Austrian legal cases I want the code "AT" to appear in the citation, calling the `jurisdiction` variable (as expected) returns the abbreviation of the very subjurisdiction.
- looking at the abbreviation sources reveals that where the top-most level jurisdiction is not used in court abbreviations, there’s no `abbrev` at all. So, nothing is rendered by this call. What’s more, this `abbrev`, if it exists, is not necessarily the country code as expected for marking the country.

**Comment by fbennett** [comment]
Sorry, that was incomplete. You also have a variable "country" to work with
in the same way. It may serve your use case to just render it without
form="short" and with text-case set to uppercase (I forget the exact
argument).

**Comment by georgd** [comment]
Oh, that’s really neat. Just what I need :)
