### ISSUE TITLE
Test for top-level jurisdiction

### ISSUE THREAD

**Issue by georgd** [Juris-M/citeproc-js#163]
I was about to declare a first release but I had forgotten about bibliography sorting.

The rules (roughly) say: per document-type (statutes or case-law) to compile a list of cited items, each grouped by jurisdictions, where international bodies come first, then the Austrian documents and after that all other nations’ documents. In the case of type `legal_case` I’m running into the sub-jurisdiction problem I mentioned earlier: I’m not able to group all the Austrian cases together because testing for `jurisdiction="at"` only returns true for legal cases that are indeed in the top-level jurisdiction. It looks like I’d have to add a test for each and every sub-jurisdiction to get them all together:

```xml
<if jurisdiction="at at:burgenland at:graz at:graz:graz at:graz:graz:deutschlandsberg at:graz:graz:feldbach [and many dozens more]" match="any">
```

The test at https://github.com/Juris-M/citeproc-js/pull/162 shows:

- The ECJ case doesn’t sort correctly (testing for `jurisdiction="eu.int"` doesn’t return true for `eu.int:cjeu`) — That’s not so big of a problem as the `eu.int` jurisdiction only has two sub-jurisdictions in the LRR.
- The LG Feldkirch case looks not so much displaced, by coincidence: after the Austrian cases, the other nations are sorted alphabetically and as the jurisdiction here is `at:innsbruck:feldkirch` which is quite at the beginning of the alphabet there aren’t many jurisdictions the could interfere. Now, inside the Austrian block of legal cases, they should be sorted first by type of court (civil and criminal courts or administrative courts) and then by hierarchy. Therefore, the `lg`, a civil and criminal court, should be listed after the `ogh`, the supreme court in the hierarchy of civil and criminal courts.

**A possible solution**

The test syntax could be enhanced by a starred jurisdiction test which returns true for the jurisdiction itself and all of its sub-jurisdictions: `jurisdiction="at*"` would return true for jurisdiction `at` and all its sub-jurisdictions. Likewise, `jurisdiction="eu.int*"` would return true for all the `eu` jurisdictions. I don’t know if this is needed but it could also be used further down the tree, like `jurisdiction="at:graz*"` returning `true` for jurisdictions `at:graz`, `at:graz:graz`, `at:graz:graz:deutschlandsberg`,... but not for jurisdiction `at`.

**Comment by fbennett** [comment]
Seems like the simplest solution would be to add a "country" test. I'll fold that into the next update. (In fact, there is a validation constraint on "jurisdiction" that limits it to country IDs, and that makes it pretty much useless.)

**Comment by georgd** [comment]
> Seems like the simplest solution would be to add a "country" test. I'll fold that into the next update.

Sounds good. Thanks!

> (In fact, there is a validation constraint on "jurisdiction" that limits it to country IDs, and that makes it pretty much useless.)

Indeed, I’ve been hit by this already as I test for `eu.int:cjeu` at a few places.

**Comment by fbennett** [comment]
The ``country`` test has been deployed.
