### ISSUE TITLE
cs:alternative and friends (tentatively) deprecated

### ISSUE THREAD

**Issue by georgd** [Juris-M/citeproc-js#165]
@fbennett I saw your deprecation note of '`cs:alternative` and friends' at https://github.com/Juris-M/citeproc-js-docs/commit/eb374d12b8c219dd518cd04973ffc31e6711948d# together with the indication of preferring the parallel-citations mechanisms. I thought, `cs:alternative` was not only for citing original and translated versions of a work but also for providing translation or translitteration of certain item-data in a citation. In the first case, I agree that using the parallel citations might be preferrable. However, in the latter, I doubt so — but you probably also have a solution for that already? (CSL 1.1 might or might not add an object structure for that as in https://github.com/citation-style-language/schema/issues/327#issuecomment-666716205)

The IBFD style requires the English translation of a foreign language title to be given after the original title in square brackets as in https://github.com/georgd/jm-style-tests/blob/jm-ibfd/jm-ibfd-with-page-label/nationalLegislationAT_test005.txt. I started to implement it by use of `cs:alternative` (unsuccessfully, as of yet, but that doesn’t scare me away) at https://github.com/georgd/jm-styles/commit/7ba72d2a15160b35a2ba8162e2a622338f3e1cd8.

Could you please enlighten me? This functionality is deprecated and not yet removed from the processor?

**Comment by denismaier** [comment]
Oh. That's sorry of bad news. I was hoping that something like this could be ported to vanilla csl. Honestly,  parallel citations take their own merits, but the advantage of the alternative mechanism is/was that information about a translation is encapsulated in one item, so you need to cite only one item. Depending on the situation, that's really useful.

**Comment by fbennett** [comment]
Hello @georgd and @denismaier!

I touched only the documentation: the processor will still run the elements as documented, and they will still validate. I'm not sure whether all of the effects that use ``cs:alternative`` can be achieved by other means, but it's worth exploring that. We may find better solutions. Perhaps the docs should have a middle category of "experimental and subject to change," which is more the thought on this one. If there were heavy reliance on the pattern and it came to be superseded, that would be painful, so some sort of caution seems appropriate.

**Comment by georgd** [comment]
I’m sorry, I didn’t mean to cause uproar. Thanks for explaining!

Anyway, I can see now that what I’m doing with the functionality is not quite what it was constructed for—but it works so far :)

**Comment by fbennett** [comment]
Not at all! I haven't been great at communication, sorry for causing alarm. For the braced-translation-after-original, that sort of effect is what the Jurism multilingual selections (processor options outside of CSL) are meant to address. Does it not work properly for that case? (We may have been over this before, re presenting variants in citations vs bibliography? If so, I can bump that up in the todo list.)

**Comment by georgd** [comment]
Frank Bennett <notifications@github.com> schrieb am Di., 6. Okt. 2020,
01:14:

> Not at all! I haven't been great at communication, sorry for causing
> alarm. For the braced-translation-after-original, that sort of effect is
> what the Jurism multilingual selections (processor options outside of CSL)
> are meant to address. Does it not work properly for that case?
>
I only stumbled over the term `processor directives` yesterday. I have no
idea how it should work. Could you please indicate what I have to do?

**Comment by fbennett** [comment]
In the client, it's done from the Langs tab of Preferences, setting translation (lang?) for title elements, and selecting a language or languages from which to supply the translation. In item data, language variants are set (for languages registered via, again, the Langs tab) with a right-click on the Title field.

In tests ... I'll need to document it. The options are a bit too fussy to safely relate from memory. Will try to do that soon.

**Comment by georgd** [comment]
OK, that’s what the checkboxes are there for. :)

So, there’s no way to control that formatting in the style, right? The brackets have to be put manually by the user?

**Comment by fbennett** [comment]
> So, there’s no way to control that formatting in the style, right? The brackets have to be put manually by the user?

Yes, that's right. That can be seen as a feature rather than a bug, to the extent that it covers user needs: it permits (one sort of) multilingual support to be layered onto any style.

**Comment by georgd** [comment]
That’s ok, I think. 

I’m trying the feature while replying and I just did move the mouse pointer slowly over the checkbox and magically ... :D So, it’s more than just ok! So, the only thing that needs more attention from the users is that they have to switch the translation on/off depending on the style.

**Comment by denismaier** [comment]
For the IFBD thing, the variants are indeed the right thing.  I always understood the alternative mechanism for published translations, reprints, etc. Is that correct? But in some tests there are some overlaps. Perhaps we should start clarifying all that a bit...
