### ISSUE TITLE
[Bug] - Setting undefined values to Item causes reproducible uncaught exceptions to be thrown

### ISSUE THREAD

**Issue by dsifford** [Juris-M/citeproc-js#17]
There are two specific locations that set item fields to `undefined` when those specific fields aren't available.

The first is here: https://github.com/Juris-M/citeproc-js/blob/master/citeproc.js#L2849

The second is here: https://github.com/Juris-M/citeproc-js/blob/master/citeproc.js#L2897

This causes very reproducible instances of uncaught exceptions being thrown, specifically at this location: https://github.com/Juris-M/citeproc-js/blob/master/citeproc.js#L10667

Error message is: `"Cannot set property 'top' of undefined"`

I think the check is backwards, no? Any thoughts?

**Comment by dsifford** [comment]
On line 10667 it's trying to access `state.tmp.name_node.top` -- `name_node` is not defined.

I tried stepping through the code a few times, but I just can't understand it. Too many side effects to be able to reason about it.

Here's what I'm giving it for the first argument of `processCitationCluster`

![image](https://cloud.githubusercontent.com/assets/5240018/18447924/ad33fa04-78f6-11e6-8607-cea50971876d.png)


And here's the CSL object that citeproc gets using the `sys` getter function

![image](https://cloud.githubusercontent.com/assets/5240018/18447984/fb2d36e4-78f6-11e6-94ee-9ac03d49456a.png)


No idea why this wouldn't work.

**Comment by dsifford** [comment]
Update: This only seems to trigger when there's no author. If I add some random author to the citation, this doesn't get triggered.

Should that happen? Lots of publications don't have known authors.

**Comment by dsifford** [comment]
Update again:

This seems to be resolved if I just make the `authors` property in the CSL JSON an array containing a single empty object.

Is there a way to fix this? This shouldn't be necessary, IMHO.

**Comment by fbennett** [comment]
The test suite contains many fixtures with no author, so this is not due to an oversight. To be sure, I retyped the input data shown in your screenshot above and built a test fixture around it with some simple CSL that exercises the spot in the code where your getting the error. The test passes fine:

    https://github.com/Juris-M/citeproc-js/blob/master/tests/fixture/local/bugreports_FailWithNoAuthor.txt

The test framework doesn't spoof-in empty author objects behind the scenes. Here is the data fetched by `retrieveItem()`:
``` javascript
{
  "URL": "https://www.aliem.com/2016/air-series-procedures-module-2016/",
  "accessed": {
    "year": 2016,
    "month": 9,
    "day": 12
  },
  "container-title": "ALiEM",
  "id": "259rb7a0",
  "issued": {
    "year": 2016,
    "month": 9,
    "day": 12
  },
  "title": "AIR Series Procedures Module (2016)",
  "type": "webpage"
}
```
Here is the citation data used to call the item, again as seen by the processor:
``` javascript
{
  "citationID": "CITATION-1",
  "citationItems": [
    {
      "id": "259rb7a0"
    }
  ],
  "properties": {
    "noteIndex": 0
  }
}
```
The style is unlikely to make a difference, but let's check that next. What style are you using when the error is thrown?

**Comment by fbennett** [comment]
(Another thought is that the object might again have become observable in other code? If that turns out to be the case, I have an idea on how to fix it in the processor, and maybe get a small efficiency gain. Certainly that's a nasty potential gotcha that would be good to eliminate.)

**Comment by dsifford** [comment]
Hey there. Thanks for checking into this.

The first thing I'm noticing is that your getter function retrieves data a slightly different shape than mine. Specifically, the dates. This likely has nothing to do with the issue, but just throwing that out there. Didn't know that other format was possible. When I originally checked out the JSON schema, it appeared to be pretty strictly enforced in the format I used. But oh well, good to know.

> I retyped the input data shown in your screenshot above and built a test fixture around it with some simple CSL that exercises the spot in the code where your getting the error. The test passes fine

Very strange. It's likely nothing to do with the lines of code that I linked to above then, but rather that's just the first place that the bug shows itself. Much trickier!

> The style is unlikely to make a difference, but let's check that next.

`american-medical-association.csl`

> Another thought is that the object might again have become observable in other code? 

I completely dereference all observables at each point in the code that interfaces with citeproc (unless there's another spot somewhere I forgot or wasn't aware of). That's a good idea since this issue is slightly similar to the one I had last time that ended up being the result of passing observables.

Not sure what to try next. Like I said, for now just adding an array with an empty object works.

**Comment by fbennett** [comment]
Aha. The error turns up with that style. So a confirmed bug in the processor - I'll post again when it's fixed.

**Comment by dsifford** [comment]
Woot woot! 

I've said it before and I'll say it again: You are the man!

Thanks so much 😄

**Comment by fbennett** [comment]
I made the mess in there, and a lot of projects depend on it, so it's good to get these fixed. Really surprised that this one wasn't reported earlier.

All set now, processor tag 1.1.126 should work for you.

**Comment by dsifford** [comment]
@fbennett Tested it out and it seems to be working great.

One thing that I do notice now (which could be unrelated to _this_ fix, but is likely related to at least one of the last 3 versions that you pushed out) is that changing the citation style is orders of magnitude slower than versions past. 

It's seemingly _seconds_ slower, which seems pretty gigantic. Even changing the citation style of a document containing just a single citation takes ballpark ~3 seconds, where it used to take milliseconds.

Just tossing that out there.

**Comment by fbennett** [comment]
Good to hear. I couldn't think of anything that would slow it down, and the test suite (1262 fixtures, each building the processor from scratch) still runs in 31 seconds on an aging Intel Core2 Duo @ 2.66 ghz.

**Comment by dsifford** [comment]
Yeah, strange indeed. No worries, working great now!

> Intel Core2 Duo

Whooooa! You should donate that to the smithsonian! 😂

**Comment by dsifford** [comment]
Saw your latest commit:

> Reverse citation dereference from 1.1.127.

Run into some problems?

**Comment by fbennett** [comment]
Yep! Zotero was relied on observing a change in the citation object in
their WYSIWYG preview editor. Their code could pull the object out of the
processor instead, but as I burned them with the change, and as it's not
critical at your end, I just wound it out.
