### ISSUE TITLE
By-name Disambiguation and non-dropping particles

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#171]
See https://github.com/citation-style-language/test-suite/pull/45

Currently, by-name disambiguation is triggering even if the names differ on their non-dropping particles with demote-non-dropping-particle="never". For example `(R. G. dos Santos et al., 2016; B. W. L. Santos et al., 2020)` instead of `(dos Santos et al., 2016; Santos et al., 2020)`

**Comment by fbennett** [comment]
Fixed.
