### ISSUE TITLE
updateUncitedItems does not purge unlisted uncited items when no citation were ever done

### ISSUE THREAD

**Issue by dgervalle** [Juris-M/citeproc-js#172]
According to the documentation of updateUncitedItems, uncited items not listed in the argument are removed from the registry.

In registry.js, the doPurge method contains the condition:
```javascript
CSL.Registry.prototype.dopurge = function (myhash) {
...
        if (this.citationreg.citationsByItemId) {
            if (!this.citationreg.citationsByItemId[this.mylist[i]] && !myhash[this.mylist[i]]) {
...
};
```
With such condition on the availability of this.citationreg.citationsByItemId, no uncited item would be deleted if there where no citation so far. IMO, the condition should be updated like this:
```javascript
CSL.Registry.prototype.dopurge = function (myhash) {
...
        if ((!this.citationreg.citationsByItemId || !this.citationreg.citationsByItemId[this.mylist[i]]) && !myhash[this.mylist[i]]) {
...
};
```
So that, if no citation where done so far, all uncited items that are unlisted are removed properly from the registry.
To also cleanup the uncited array, I would also add inside that condition:
```javascript
delete this.uncited[this.mylist[i]];
```

If you don't see any cons, I would be pleased if you could integrate those changes, so that I avoid a fork for such a minor change.

**Comment by fbennett** [comment]
Thanks for this report, and for the recommended fix. I will merge this.

**Comment by fbennett** [comment]
Adopted in https://github.com/Juris-M/citeproc-js/commit/2a133d247e3fad9c9c0b42a6f892c3a7cb24a71f
