### ISSUE TITLE
APA-style subtitle capitalization shouldn't apply to words with internal capitalization

### ISSUE THREAD

**Issue by dstillman** [Juris-M/citeproc-js#178]
> For instance, this paper (https://pubmed.ncbi.nlm.nih.gov/30217542/) is rendered as "A face is more than just the eyes, nose, and mouth: FMRI evidence that face-selective cortex represents external features." It should be "fMRI."

https://github.com/zotero/zotero/issues/1958

**Comment by fbennett** [comment]
Code: https://github.com/Juris-M/citeproc-js/blob/master/src/formatters.js#L279
Test suite: https://github.com/citation-style-language/test-suite 
Can advise if necessary.

**Comment by dstillman** [comment]
Oh, so it seems like this is just a general problem of title casing not respecting internal capitalization, not a problem with subtitle capitalization specifically. I can reproduce this with Chicago style.

I can fix this, but I'm somewhat surprised by it — I would think we'd be getting reports all the time of things with internal capitalization (e.g., "iPhone") getting incorrectly capitalized in title-case styles. I wonder if some styles do actually call for naive title-casing, regardless of internal capitalization.

**Comment by dstillman** [comment]
https://whoo.ps/2013/10/23/how-do-you-capitalize-iphone-or-ipad quotes the Chicago guide on this:

> Brand names or names of companies that are spelled with a lowercase initial letter followed by a capital letter (eBay, iPod, iPhone, etc.) need not be capitalized at the beginning of a sentence or heading, though some editors may prefer to reword.

**Comment by bwiernik** [comment]
What you're saying is correct @dstillman and should be fixed in the spec

**Comment by dstillman** [comment]
Sorry, I don't know how to build citeproc-js or write tests, but here's a patch that seems to fix this problem. It checks to see if a word is all lowercase (i.e., no existing capitalization), and only then does it capitalize.

If someone who knows how to do the above is able to test and merge this, I'd appreciate it.

```diff
diff --git a/chrome/content/zotero/xpcom/citeproc.js b/chrome/content/zotero/xpcom/citeproc.js
index 34020a9ef..7bf751d39 100644
--- a/chrome/content/zotero/xpcom/citeproc.js
+++ b/chrome/content/zotero/xpcom/citeproc.js
@@ -21946,23 +21946,29 @@ CSL.Output.Formatters = (function () {
                     var words = wordle.strings;
                     for (var j=0,jlen=words.length;j<jlen;j++) {
                         var word = words[j];
                         if (!word) {
                             continue;
                         }
-                        if (word.length > 1 && !CSL.toLocaleLowerCase.call(state, word).match(config.skipWordsRex)) {
+                        let lcase = CSL.toLocaleLowerCase.call(state, word);
+                        let capitalize = false;
+                        if (word.length > 1 && !lcase.match(config.skipWordsRex)) {
                             // Capitalize every word that is not a stop-word
-                            words[j] = _capitalise.call(state, words[j]);
+                            capitalize = true;
                         } else if (j === (words.length - 1) && followingTag === "-") {
-                            words[j] = _capitalise.call(state, words[j]);
+                            capitalize = true;
                         } else if (config.isFirst) {
                             // Capitalize first word, even if a stop-word
-                            words[j] = _capitalise.call(state, words[j]);
+                            capitalize = true;
                         } else if (config.afterPunct) {
                             // Capitalize after punctuation
-                            words[j] = _capitalise.call(state, words[j]);
+                            capitalize = true;
+                        }
+                        // Don't capitalize if word already contains capitalization
+                        if (capitalize && word === lcase) {
+                            words[j] = _capitalise.call(state, word);
                         }
                         config.afterPunct = false;
                         config.isFirst = false;
                         config.lastWordPos = {
                             strings: i,
                             words: j
@@ -21991,13 +21997,16 @@ CSL.Output.Formatters = (function () {
             capitaliseWords: function(str) {
                 var words = str.split(" ");
                 for (var i=0,ilen=words.length;i<ilen;i++) {
                     var word = words[i];
                     if (word) {
                         if (config.isFirst) {
-                            words[i] = _capitalise.call(state, word);
+                            // Don't capitalize if word already contains capitalization
+                            if (word == CSL.toLocaleLowerCase.call(state, word)) {
+                                words[i] = _capitalise.call(state, word);
+                            }
                             config.isFirst = false;
                             break;
                         }
                     }
                 }
                 return words.join(" ");
@@ -22021,13 +22030,16 @@ CSL.Output.Formatters = (function () {
             quoteState: [],
             capitaliseWords: function(str) {
                 var words = str.split(" ");
                 for (var i=0,ilen=words.length;i<ilen;i++) {
                     var word = words[i];
                     if (word) {
-                        words[i] = _capitalise.call(state, word);
+                        // Don't capitalize if word already contains capitalization
+                        if (word == CSL.toLocaleLowerCase.call(state, word)) {
+                            words[i] = _capitalise.call(state, word);
+                        }
                     }
                 }
                 return words.join(" ");
             },
             skipWordsRex: null,
             tagState: [],
```

**Comment by dstillman** [comment]
OK, I figured out how to build citeproc-js and run tests. Currently failing on two tests:

```
  1508 passing (11s)
  2 failing

  1) Integration tests should pass bugreports_SelfLink:

      AssertionError: /Users/dan/citeproc-js/fixtures/std/processor-tests/humans/bugreports_SelfLink.txt
      + expected - actual

      -[o A. <i>Book Title</i>]
      +[O A. <i>Book Title</i>]

      at Context.<anonymous> (.cslTestFixtures/fixtures.js:87240:24)
      at processImmediate (internal/timers.js:461:21)

  2) Integration tests should pass bugreports_SingleQuoteXml:

      AssertionError: /Users/dan/citeproc-js/fixtures/std/processor-tests/humans/bugreports_SingleQuoteXml.txt
      + expected - actual

      -[Cite with a composer ; o A. "hello" <i>Book Title</i>]
      +[Cite with a composer ; O A. "hello" <i>Book Title</i>]

      at Context.<anonymous> (.cslTestFixtures/fixtures.js:87240:24)
      at processImmediate (internal/timers.js:461:21)
```

Looking into how I caused those.

**Comment by dstillman** [comment]
Those errors are caused by the patch to capitaliseWords(), but I'm not understanding that at all — if my patch is conditionally <em>not</em> capitalizing when the string isn't all lowercase, when before it was always capitalizing, I don't understand how that's causing a lowercase "o" to be capitalized when it wasn't before. That seems…backwards?

I'm going to have to set this aside for the moment, so if someone else wants to take a crack at it, go for it.

**Comment by bwiernik** [comment]
@dstillman You are reading the output backwards. After your patch, the o is **not** being capitalized, but it should be capitalized.

**Comment by dstillman** [comment]
Oh, I was, but someone should fix that patch output —  it lists `+ expected - actual` above and then displays actual before expected below. At the very least the order should be the same, but I would say `-` should be expected and `+` should be actual.

**Comment by fbennett** [comment]
Someone has done that.
https://github.com/Juris-M/citeproc-test-runner/commit/10ac0a0c6ad09f0b9dabb59631ec927d6654def6

**Comment by fbennett** [comment]
Someone did not read carefully, and has now reverted their change.
https://github.com/Juris-M/citeproc-test-runner/commit/679a0490fd0082ac70f517701662ad4955012588
The output is directly from Mocha. If it's a problem, it's an issue for upstream.

**Comment by fbennett** [comment]
I've added a fix for the capitalization issue. https://github.com/Juris-M/citeproc-js/commit/aa2683f48fe23be459f4ed3be3960e2bb56203f0
In the two test failures flagged, the target of the `textcase` operation was a term containing a non-breaking space. This was not recognized as a split-point, so the term was treated as a single word containing uppercase characters and ignored. In addition to the fix for capitalization of cute product names etc etc, the commit invokes markup splitting in the `capitalize-all` and `capitalize-first` functions, rather than simply splitting on a space character, which was a bug report waiting to happen.

Closing this. Feel free to reopen at will if it's still broken and messed up (in addition to being ugly).
