### ISSUE TITLE
Negative year date parsing

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#18]
Currently, Zotero doesn't properly parse negative years (it just strips the negative sign and returns a positive year). I tried to use the recently updated date override method with the Propachi plugin (with citeproc-js .136). The processor correctly receives the negative year. However, the year is rendered as a simple negative number, rather than correctly displaying the BCE abbreviation.

e.g., with `issued: -323` in the `Extra` field, the reference renders as:
Smith, J. (-323) _Title._ 

Is there a way to get citeproc-js to properly render negative years?

**Comment by fbennett** [comment]
This is now (partially) fixed in processor version 1.1.150, available in Propachi latest.

The fix only applies to single years. Ranges and dates with month or month/day will still fail. On the plus side, the fix will wake up the "AD" suffix on small-value years (same restrictions apply).
