### ISSUE TITLE
Few possible bugs

### ISSUE THREAD

**Issue by dsifford** [Juris-M/citeproc-js#19]
Hey Frank,

I've been tracking uncaught exceptions across all installations of my application and these three seem to be coming up regularly:

**(Edit 10/15/16 - Fixed.)** ~~https://github.com/dsifford/academic-bloggers-toolkit/issues/175~~
**(Edit 10/16/16 - Wontfix.)** ~~https://github.com/dsifford/academic-bloggers-toolkit/issues/176~~
https://github.com/dsifford/academic-bloggers-toolkit/issues/177

I've played around with this and I just can't seem to figure out what could be happening? Any ideas?

**Comment by fbennett** [comment]
The first seems like an error on bad input (a citation object should always have a "properties" property, and the processor won't strip it).

On the other two, the only thing I can think of is that the "sys" object might be getting clobbered during instantiation there, if the user has rapidly switched between styles and the processor is running async.

**Comment by dsifford** [comment]
@fbennett Thanks for the feedback. Totally throwing a hail mary at this point. I've been getting these three in particular the most (generally about ~3 times a week from a range of different sites). No idea what could be going on...

I've tried reproducing a few times but can't.

What's interesting is that, to my knowledge, there is no way citeproc could be getting citation object without "properties"...

[This line](https://github.com/dsifford/academic-bloggers-toolkit/blob/master/src/lib/js/reference-list/components/ReferenceList.tsx#L251) makes a call to [this function](https://github.com/dsifford/academic-bloggers-toolkit/blob/master/src/lib/js/utils/CSLProcessor.ts#L99) just before the call to `processCitationCluster` is made and that function _always_ returns an object containing a `properties` parameter.

Suuuuper super strange.

I'll keep you posted if I'm able to turn something up.

**Comment by dsifford** [comment]
Update: Figured out dsifford/academic-bloggers-toolkit#175

This one turned up when people altered the html of citations. In some cases, the processor would be getting a citationId that didn't exist (so it would throw an error) and in other cases, the processor would be getting a citation object without an ID altogether (which would obviously also trigger an error). 

I've added two checks for this on my end: one to guard against extra citations that don't belong, and the other to guard against citations that were stripped of their ID. 

We can call that one good! Nothing you can do except maybe skip it on your end to prevent the exception. Your call there.

I'll keep you posted on the other two when I figure them out.
