### ISSUE TITLE
Given names are not abbreviated when using apa

### ISSUE THREAD

**Issue by dohool** [Juris-M/citeproc-js#192]
Hello,

I have encountered a problem with citeproc.js regarding the style apa.

With the apa style I expect all first names to be abbreviated. This does not work for the following minimal example:

```
{
  "14569": {
    "type": "thesis",
    "id": "14569",
    "categories": [],
    "author": [
      {
        "family": "Smith",
        "given": "John"
      }
    ],
    "issued": {
      "date-parts": [
        [
          "2016",
          "1",
          "1"
        ]
      ]
    },
    "title": "Title 1"
  },
  "35292": {
    "id": "35292",
    "categories": [],
    "author": [
      {
        "family": "Smith",
        "given": "J."
      }
    ],
    "issued": {
      "date-parts": [
        [
          "2014",
          "1",
          "1"
        ]
      ]
    },
    "title": "Title2"
  }
}

```

Result:

```
Smith, J. (2014). Title2.
Smith, John. (2016). Title 1.
```

The second name is not abbreviated. However, if I modify the minimal example so that both first names are fully spelled out, both first names are abbreviated in the result.

```
Smith, J. (2014). Title2.
Smith, J. (2016). Title 1.
```

Is this an error, or am I not understanding something correctly here?

**Comment by bwiernik** [comment]
I do not see that behavior with apa.csl (APA 7th edition), eg, see https://zbib.org/ffa032e80add4fecb0fa2ffc491fd1a2

For APA 6th edition, not abbreviating in order to disambiguate the different authors with the same initials but different names is the expected behavior according to the CSL style code and the APA 6 manual.
