### ISSUE TITLE
Double-encoded angle brackets in HTML

### ISSUE THREAD

**Issue by dstillman** [Juris-M/citeproc-js#2]
```json
[
	{
		"id": "http://zotero.org/users/local/0rmqTjvx/items/ABCD2345",
		"type": "webpage",
		"title": "Zotero Quick Start Guide",
		"URL": "http://zotero.org/support/quick_start_guide",
		"author": [
			{
				"literal": "Center for History and New Media"
			}
		]
	}
]
```

Citing with https://www.zotero.org/styles/universite-libre-de-bruxelles-histoire?source=1

Rendered HTML from 1.1.74:

``CENTER FOR HISTORY AND NEW MEDIA, « Zotero Quick Start Guide », s.d., [En ligne]. &lt;http://zotero.org/support/quick_start_guide&gt;. .``

i.e., markup is ``[En ligne]. &amp;lt;http://zotero.``

Correct in 1.1.60

**Comment by fbennett** [comment]
Thanks, sorry for missing that. Fixed by 1cb23ca.
