### ISSUE TITLE
Title Caser errors

### ISSUE THREAD

**Issue by retorquere** [Juris-M/citeproc-js#20]
These two titles don't title-case properly:
1. "Using Google Flu Trends data in forecasting influenza-like-illness related ED visits in Omaha, Nebraska" (Influenza-like-Illness) doesn't capitalize "like")
2. "Using networks to combine “big data” and traditional surveillance to improve influenza predictions" ("big" is not capitalized)

**Comment by fbennett** [comment]
Thanks for the reminder. I really do need to get this one fixed.

**Comment by fbennett** [comment]
These should be fixed as of ab147e2fa29c18c81a35ec007cbb2849c83e5578.
