### ISSUE TITLE
page-range-format="chicago-15" not supported

### ISSUE THREAD

**Issue by adam3smith** [Juris-M/citeproc-js#206]
Moving issue from https://github.com/citation-style-language/styles/issues/5926

Validating 1.0.2 styles with `page-range-format="chicago-15"` throw an error with 

```
Error generating citations and bibliography:
TypeError: me.fun.page_mangler is not a function
```

[Sample style here](https://gist.githubusercontent.com/POBrien333/bc9f598282a97e11d061c30457773d99/raw/1925f9de12dead26105c509ab1062009dab06053/international-journal-of-cosmetic-science.csl)

**Comment by zepinglee** [comment]
Both `chicago-15` and `chicago-16` from CSL v1.0.2 are not implemented yet.

P.S. I've created the test file for `chicago-16`: <https://github.com/zepinglee/test-suite/blob/chicago-16/processor-tests/humans/page_Chicago16.txt>.

**Comment by larsgw** [comment]
I think I can work on implementing that if no one else is.

**Comment by adam3smith** [comment]
@larsgw -- that'd be wonderful

**Comment by larsgw** [comment]
@zepinglee Could you make a pull request to add the test case to https://github.com/citation-style-language/test-suite?

**Comment by zepinglee** [comment]
> @zepinglee Could you make a pull request to add the test case to https://github.com/citation-style-language/test-suite?

OK. <https://github.com/citation-style-language/test-suite/pull/49>
