### ISSUE TITLE
Update bundle files

### ISSUE THREAD

**Issue by zepinglee** [Juris-M/citeproc-js#213]
As pointed out in <https://github.com/Juris-M/citeproc-js/pull/208#issuecomment-1166676656>, the two bundle files `citeproc.js` and `citeproc_commonjs.js` have not been updated in a while. This causes some features in CSL v1.0.2 not merged (e.g.,new roles and Chicago-16 page-range-format) and they are also missing in Zotero. See <https://github.com/Juris-M/citeproc-js/commit/41f3cc5b7f9eb42aba31bc9ab240c811c8dcf117> for detailed changes. Shall I make a PR?

@bwiernik

**Comment by larsgw** [comment]
I would also recommend making a new npm release after this, if that is possible.
