### ISSUE TITLE
[Serious Bug]: processCitationCluster returns invalid HTML IDs.

### ISSUE THREAD

**Issue by dsifford** [Juris-M/citeproc-js#22]
Hi Frank,

Starting about an hour ago, `processCitationCluster` has started regularly returning HTML IDs that begin with an integer. This causes a meltdown of my plugin because it depends on valid HTML selectors.

Can you please consider changing your ID generator to one that returns HTML IDs that begin with a character?

Here's the one I use for reference: 

``` js
export function generateID(): string {
    return String.fromCharCode(97 + Math.floor(Math.random() * 26)) + Math.round(Math.random() * Date.now()).toString(30); // tslint:disable-line
}
```

**Comment by dsifford** [comment]
Update: The "serious" part of this has been fixed on my end. So I'm all good!

But yeah, HTML IDs must begin with a letter and not an integer.

**Comment by fbennett** [comment]
Thanks for the heads-up. These are citationIDs? Those are the only ones I can think of that are automatically generated, when missing from the input. They aren't constrained by assumptions about acceptable values, and the code for generating them was last edited five years ago.

It shouldn't be a problem to add a non-numeric value to the front of the ID strings. I'll include that change in the next release.

**Comment by dsifford** [comment]
Yep! Sorry for the urgency in my first message by the way (that was me scrambling!)

Specifically, the IDs are at index [1][2] of the tuple returned by processCitationCluster. It's the HTML ID for a single inline citation item (at least, that's what I've been using it for).
