### ISSUE TITLE
Localizing commas, colons, and semicolons

### ISSUE THREAD

**Issue by josephdangerstewart** [Juris-M/citeproc-js#221]
Does this library support localizing commas, colons, and semicolons (specifically in name or group delimiters)?

[This PR](https://github.com/citation-style-language/schema/pull/144) added commas and semi colons to the CSL schema in mid-2020 although I don't know if the replacement strategy was ever decided on (though it was proposed to just indiscriminately replace all commas, colons, and semicolons with the localized version).

I have the following CSL added [here](https://github.com/citation-style-language/locales/blob/6b0cb4689127a69852f48608b6d1a879900f418b/locales-zh-CN.xml#L65)

```xml
<term name="comma">，</term>
<term name="colon">：</term>
<term name="semicolon">；</term>
```

However, rendering citations in the [Chicago fullnote bibliography style](https://github.com/citation-style-language/styles/blob/master/chicago-fullnote-bibliography.csl#L113) does not localize any of the commas, colons, or semicolon.

Do I need to make a change to the citation style? Or is this just not supported currently?

**Comment by denismaier** [comment]
Sorry for the late answer. The linked PR is against the 1.1-branch. CSL is still at 1.0.2 so no support for this feature currently.

**Comment by josephdangerstewart** [comment]
Cool, thanks for the confirmation!
