### ISSUE TITLE
Q: What is embedBibliographyEntry() for?

### ISSUE THREAD

**Issue by KarlHegbloom** [Juris-M/citeproc-js#24]
I've searched the web with Google for embedBibliographyEntry, and looked at every mention of it in the citeproc code... I'm not sure what it's supposed to be used for. I made a slot for it in the \ztbibItemText macro that my "bbl" output format produces for the zotero-texmacs-integration, thinking that maybe it will need that someday... but if it's not really anything it needs, then maybe I should just remove that extraneous argument? It's always blank right now because embedBibliographyEntry is not defined anywhere.

**Comment by KarlHegbloom** [comment]
Perhaps answering my own question, at least in part, I see from the HTML output format that it's to "add decorations to bibliography output of individual items". I'm using Scheme code inside of TeXmacs to create a list of pagerefs, linking back to the points in the document where each item was cited. I suppose that it could be used for that purpose, provided that it has access to all of the necessary information.

It does not need much other than the citation cluster id pasted to the system id of the zotero database entry with some string between them to delimit them to make it visually obvious which part of the label is which... then use that as a \label within the document, so that \reference{label} or \pageref{label} will print the reference wrapped in an intra-document hyperlink:  e.g., [1, 4, 17, 28]  means the reference is cited on pages 1, 4, 17, and 28, with the links jumping to the exact points of citation.

**Comment by fbennett** [comment]
Karl (@KarlHegbloom): Sorry for the long delay in responding! Should any action be taken on this in the processor?

**Comment by KarlHegbloom** [comment]
I need access to the Zotero held information, the fieldid's as the same strings the editor --> LibreOffice + propachi-texmacs gives it when it recieves the response to documentGetFields, in combination with the already visible to variableWrapper sysid, so that for each citationcluster or editor zcite... there is for each citation in that cluster, an intra-document reference target label formed from the fieldid and the sysid, to provide ref target anchor labels for a list of pagerefs for each item in the bibliography (sysid) linking back to each citation in the document this bib item is referenced by.

How do I obtain the information from inside the variablewrapper? Or is the embedBibliographyEntry a better way? How can I make it return that list of labels, each the composition of the citationcluster zfieldid (the fieldid coming from within xpcom/integration.js of Juris-M / Zotero, defined by the editor it is integrating with) and the sysid I already see from inside the variableWrapper?

I want to return either an in document order list of those label strings, or a string join, comma separated, of them suitable for direct use as a comma separated argument list for a LaTeX macro. The idea is to make the one syntax compatible with both TeXmacs and LaTeX. I already do this in Scheme code that runs in my TeXmacs plugin, tm-zotero. (zotero-texmacs-integration in my github). I think that Zotero already knows all of the necessary information at that point, and that it will work better to have zotero return those labels. And for LaTeX it just makes sense to have zotero do that part of the work since, unlike TeXmacs which has an embedded scheme extension language, LaTeX can't as easily do that computation as can javascript inside of zotero. LaTeX can easily process that comma separated list into a string of comma separated pagerefs for typetting and pdf hyperlinks inside the document, so that clicking on the pageref number displayed in the list of them that is inserted behind each bibliography item causes a hyperlink jump to the location in the document where that item is cited. (Automagically by just having a correct label at the place being pageref'd...)

**Comment by KarlHegbloom** [comment]
A tool that can draw me a visual graph showing how the objects are all hooked up inside of zotero or any javascript program like that,  to make it easier to explore and understand the program,  and to see how to get at the information it requires.

Accessors added to those objects that own that information could then perhaps be inquired from elsewhere to obtain the needed information? Or could it be passed in to the citeproc so it can be seen from inside the variableWrapper or embedBibliographyEntry?

**Comment by fbennett** [comment]
Debugging infrastructure to this level is beyond the reach of my own programming skills. I could look at a pull request, but beyond that I can't do much to help here.
