### ISSUE TITLE
Bibliography `entry-spacing` attribute not working

### ISSUE THREAD

**Issue by thelsevier** [Juris-M/citeproc-js#243]
Hi, we have a user report of an incorrect CSL style which is missing a blank line between bibliography entries. The fix for that is updating the `entry-spacing` attribute on the `bibliography` item of the CSL file, but doing that apparently has no effect. You can test this here: https://editor.citationstyles.org/visualEditor/ - pick any style and try to set entry spacing on the bibliography to any number, it will have no effect.

Further, in our application code we amended the CSL file before use, setting the `entry-spacing` atribute to different values and the `citeproc` library yields the exact same result for `makeBibliography()`, completely ignoring the attribute value. This is using the latest version of citeproc, `2.4.63`.

Please advise on how we might be able to solve this issue. Thank you!

**Comment by thelsevier** [comment]
Looking through the code, I can see `entry-spacing` being assigned to some params in `src/api_bibliography.js` and defined in `src/attributes.js`, but nothing further. I cannot yet find where the code taking it into account is or should be. Any pointers maybe? Thanks!

**Comment by zepinglee** [comment]
The `entryspacing` attribute is in the first element returned by `makebibliography()` (see the [documentation](https://citeproc-js.readthedocs.io/en/latest/running.html#makebibliography)).

**Comment by thelsevier** [comment]
Thank you for your time @zepinglee, so the issue is on our end, just further down the line. Cheers!
