### ISSUE TITLE
appendCitationCluster flag missing?

### ISSUE THREAD

**Issue by johanneswilm** [Juris-M/citeproc-js#25]
The manual seems to say that one can set true/false as the second argument of appendCitationCluster in order to only receive one value back if one previously registered all citation sources using updateItems() [1]. Yet looking at the source code and trying it out,. it seems like the second argument is not used at all.

[1] https://github.com/Juris-M/citeproc-js/blob/22e86b46576bde2c2b78896bbe00644017d02d39/manual/citeproc-doc.rst#appendcitationcluster

**Comment by fbennett** [comment]
Sorry for the long delay! Fixed by 83e65f301795ac6b63e33855dca4d2b82267e90b -- and thanks!
