### ISSUE TITLE
Uppercase subtitle flag

### ISSUE THREAD

**Issue by fbennett** [Juris-M/citeproc-js#27]
Opening discussion here following an issue raised by @bwiernik in a [citation-style-language/styles pull request](https://github.com/citation-style-language/styles/pull/2434).

I'm wondering about one thing (opinions from @rmzelle and @adam3smith also welcome ...) Should upper-casing-of-subtitles mode be dependent on title-case, or should it be forced in all title fields regardless?

**Comment by adam3smith** [comment]
we certainly don't want to uppercase all subtitles, no -- Vancouver e.g. starts subtitles in lowercase. That's why there's the extra propachi add-on you've made. Or am I misunderstanding the question?

**Comment by bwiernik** [comment]
Yeah, I'm not following the question here.

**Comment by fbennett** [comment]
That's the ticket. My first attempt to fix quoted-capitalization triggered a bunch of test failures, and as I dug into the code, I noticed that in the Propachi Upper configuration, the first character of subtitles was uppercased independent of the `text-case="title"` attribute ... and I got confused.

That's a great run-down of the desired behaviour. I'll pick through the tests and make sure those rules are respected.

Slotting a toggle into the menu and eliminating the special plugin is a great idea. As I've been working on the plugin `bootstrap.js` already, this will be a good time to handle that. So ... lots of work for the weekend.

Kind of depressing that work put into the plugin will have to be thrown out within a year, but at least it will set a baseline for the UX in the next iteration of Zotero.

**Comment by fbennett** [comment]
Close to a solution to the quotes issue, as well as fixes for propachi-upper casing on multilingual fields (which wasn't working at all previously). Letter-case adjustments are extremely complex and sensitive, it turns out. I'll be putting the UI toggle idea off to a later point in time -- if anyone else would like to pick it up, I'll be right behind you!

More news tomorrow.

**Comment by fbennett** [comment]
The quiet struggle for adequate text-case transforms continues. Another question.

Should a word following a hyphen be capitalized, or never so?

From the tests, it looks like the processor has been shy of capitalizing a word following a hyphen. That's sometimes right, and sometimes wrong. IIRC a common rule is to capitalize if the particle before the hyphen is a full word that can stand on its own. When chemical formulae appear in titles, I think they're not supposed to be capitalized.

We can't interpret the semantics, and I don't know whether forcing is one way is better one way than the other.  In the current iteration, the code is capitalizing (and so changing the behavior).

Input very welcome on this one.

**Comment by bwiernik** [comment]
APA says to always capitalize after a hyphen if the first part is capitalized. Chicago seems to have simplified its rules to just always capitalize as well (http://www.chicagomanualofstyle.org/about16_rules.html)--@adam3smith, can you comment on that?

Users of chemical names should probably put them in no-case tags (but most physical science journals don't use title case for article titles, so not much of a problem).

**Comment by fbennett** [comment]
@bwiernik Good news to me so far, as that's exactly how the processor is behaving (apart from some other, unrelated test failures). Will wait for further feedback ...

**Comment by adam3smith** [comment]
indeed, the Chicago rules are to almost always capitalize after a hyphen. The exceptions are small enough to ignore.

**Comment by fbennett** [comment]
Rewriting the text-case="title" code. It will use a kind of state machine, and when done it will be much easier to control and debug. Should have something in a few days.

**Comment by fbennett** [comment]
Beta versions of the Propachi plugins with the new code are now available:

https://github.com/Juris-M/propachi-vanilla/releases/tag/v1.1.71beta
https://github.com/Juris-M/propachi-upper/releases/tag/v1.1.68beta

The `text-case` functions have been completely rewritten, so please try to break them. There are a couple of changes in behaviour against the old code:

* Capitalization is no longer disabled following a hyphen
* A `nocase` span tag now takes effect in `uppercase` and `lowercase` modes (it was ignored previously)
* Maybe some other little differences that I can't remember this evening

Here's hoping for the best ...

**Comment by bwiernik** [comment]
With Propachi Upper 1.1.68beta, I still don't get an uppercase letter in title-case following a quote mark:

Briscoe, Jon P.; Finkelstein, Lisa M. 2009: The “new Career” and Organizational Commitment. In: Career Development International 14,3: 242–260. [https://doi.org/10/fhs2x9].

Not sure if this was changed in the rewrite or not...

**Comment by KarlHegbloom** [comment]
I was taught to not uppercase "and". It looks right to me...

**Comment by adam3smith** [comment]
the problem in bwiernik's example is the lowercased "new". And is correctly lowercased, as you say.

**Comment by fbennett** [comment]
Great stuff, thanks! I've also had a couple of reports from Emiliano at #30. The issues with Emiliano's reports are clear. I'm not sure what's going on with the "new" here, but we'll get it fixed soon.

I'm currently working on a  rewrite of the "flipflop" in-text markup code to address a [fault report on the Zotero forums](https://forums.zotero.org/discussion/64120/sep-is-undefined#latest). I've done the stupid thing of making WIP checkins to the main branch of the repo, so fixes to text-case will need to wait until that work is done -- but I'm nearly there with flipflop, and will get it sorted soon.

There was more work in this than I expected, and the flip-flop glitch was an unhappy surprise, but the code relating to both issues will be much improved when the dust settles.

**Comment by KarlHegbloom** [comment]
Frank, maybe you should get git-wip'ed for that mistake? You oaf!
Seriously... I found this thing in the Emacs Elpa packages for a command
called git-wip that checks in every time the file is saved while it's
enabled as a minor-mode, but on a local wip branch.

**Comment by fbennett** [comment]
It's actually a years-long habit, and it's made the logs pretty cluttered. At some point I'll have to lop off old history, preserving maybe a year's worth, I may do some consolidation then.

**Comment by KarlHegbloom** [comment]
I like having github as a backup in case my laptop gets stolen, broken, or the disk fails.

Just punning about  Linus' choice name for the global information tracker thing.

**Comment by bwiernik** [comment]
New bug (not sure if it's connected to other parts you're working on):

With Propachi Upper enabled, the title gets printed twice:
Jennrich, R. I., & Bentler, P. M. (2012). Exploratory bi-factor analysis: The oblique case Exploratory bi-factor analysis: The oblique case. Psychometrika, 77(3), 442–454. https://doi.org/10.1007/s11336-012-9269-1

This occurs whether the Short Title field has content or not. Any italics or other formatting on the title is printed in the first instance, but not in the second.

**Comment by fbennett** [comment]
Nice one! That's new. Is it style-dependent?

**Comment by bwiernik** [comment]
Yes, but I can't find a pattern for when it occurs across styles:

Yes:
APA 6
Cell
Frontiers journals
IEEE
Nature
PNAS
Vancouver

No:
American Chemical Society (with titles)
Chicago (author-date)
Chicago (full note)
Comparative Population Studies
MLA 7
MHRA 3

**Comment by fbennett** [comment]
That's e ought - thanks! The quote/tag parsing stuff is nearly done, and I should be able to start digging on this tomorrow.

**Comment by bwiernik** [comment]
Double title still there for me in 1.1.68

**Comment by fbennett** [comment]
Yeah, haven't touched that yet. The rewrite of in-text markup took a couple of weeks; that's the only change in the latest release.

**Comment by bwiernik** [comment]
Okay just checking

**Comment by fbennett** [comment]
Bugs should be fixed and all should be working now.
