### ISSUE TITLE
TypeError: Cannot read property 'before' of undefined

### ISSUE THREAD

**Issue by adam3smith** [Juris-M/citeproc-js#28]
When I run citeproc-js with node.js for the cslEditor, it throws the above error for a subset of styles, e.g. ambio.csl

This is starting at version 1.1.142 and is true for all versions since. 1.1.141 works fine

Any thoughts?

**Comment by fbennett** [comment]
Able to reproduce this - and it looks like a crashing bug for production instances too. Ouch! Will get to work on a fix pronto.

**Comment by fbennett** [comment]
A variable name was misspelled. Fix pushed, will be available via Propachi soon.

**Comment by adam3smith** [comment]
Thanks -- haven't tested this yet, but glad those 40,000+ citations I calculate every time I update the editor actually helped catch a bug.

**Comment by fbennett** [comment]
They certainly saved a world of consternation on this occasion - literally.
