### ISSUE TITLE
CSL-M: How to append page numbers to inline citations? Not seeing any information on this in the docs

### ISSUE THREAD

**Issue by dsifford** [Juris-M/citeproc-js#29]
[See this thread](https://github.com/dsifford/academic-bloggers-toolkit/issues/269) for more details.

I know this is possible because I can do it in the demo on the CSL site. Just not sure how to implement.

Thanks @fbennett 😄

**Comment by fbennett** [comment]
Sorry for the delay in answering. That should certainly be in the docs, although it isn't. Nasty oversight.

The objects in `citationItems` can carry pinpoint details. There are examples among the [text fixtures](https://github.com/citation-style-language/test-suite/blob/master/processor-tests/humans/locator_SimpleLocators.txt), which show how it works fairly clearly. For articles and whatnot, you'll almost always use the `page` label. I can send a list of the possible labels if you need.

**Comment by dsifford** [comment]
Thanks for the clarification! I'll check this out later this week and chime back if there's anything in particular that's still confusing (though, I'm fairly sure I'll be able to figure it out if you used it in your tests).
