### ISSUE TITLE
Citation only, no wrapped html -- How do I make this happen?

### ISSUE THREAD

**Issue by dsifford** [Juris-M/citeproc-js#3]
In the demo, the response object returned from `makeBibliography` is an array of html..

```
<div class="csl-entry"> <div class="csl-left-margin">1. </div><div class="csl-right-inline">Knuth DE. <i>Digital Typography</i>. Center for the Study of Language and Information; 1998.</div> </div>
```

How do I get it to return JUST the inner formatting? I want to handle the presentation myself.

This is what I want:
```
Knuth DE. <i>Digital Typography</i>. Center for the Study of Language and Information; 1998.
```

Any help is apprecitated! Thanks

**Comment by fbennett** [comment]
Is there are reason you can't use CSS to control the display effects of the div wrappers? In some styles they are important to the structure of the cite. If you do want to omit them completely, you could extend src/formats.js with a custom output format that sets the HTML but returns unadorned text instead of the div wrappers.

**Comment by dsifford** [comment]
I'd like just the citation content because my app takes it and throws it into an ordered list. By doing so, it'll get numbered twice.

I suppose, now that I think about it more, I could just be tossing the citations into a containing `<div>`. I'll have to play around with it more.

One other question comes to mind now that I'm thinking about html formatting. Does citeproc also return correctly formatted inline citations? If so, how do I access them? (All I really am aware of is the `makeBibliography` function).

Thanks for the help!

**Comment by dsifford** [comment]
Ah, now I remember the reason...

I'm generally grabbing citations one at a time (but also sometimes 2-3 at a time, and other times 10-20 at a time). I didn't think it was possible for it to keep the numbering in sync if it had to process the data more than in one go. 

If this is possible, I'm totally interested.

**Comment by dsifford** [comment]
FWIW, this is how I'm doing it right now:

```ts
/**
     * Removes outer HTML formatting served from citeproc, sparing inner `<i>` or `<a>` tags.
     * @param  {string} ref The reference payload from citeproc.
     * @return {string}     A formatted reference string without outer HTML.
     */
    trimHTML(ref: string): string {
        return ref
            .replace(/<(?!(i|\/i|a|\/a)).+?>/g, '')
            .trim()
            .replace(/^\d+\.\s?/, '');
    }
```
