### ISSUE TITLE
citeproc-js & Academic Blogger's Toolkit

### ISSUE THREAD

**Issue by fbennett** [Juris-M/citeproc-js#31]
Derek (@dsifford): Might you be tempted to extend ABT to support legal referencing? I have some ideas, would like to bounce them off you when you have time.

**Comment by dsifford** [comment]
Yep, sounds good to me. Let me know what you have in mind.

**Comment by fbennett** [comment]
It seems like well documented discourse about law is likely to become a thing over the next few years, and ABT seems like a terrific platform for it.

That's just my personal enthusiasm speaking, though, and it would be wasteful of your time to bend the code through the necessary hoops unless it's going to have impact. I'm checking around with some people to test the waters, and will check back when I have a sense of how it might be received by lawyers-who-do-tech.

**Comment by dsifford** [comment]
@fbennett I think your intuition is probably correct.

The codebase is pretty flexible, so it shouldn't be much of a problem to add more features for Law bloggers.

Keep me posted.

**Comment by fbennett** [comment]
Closing this for now -- one for later, perhaps, when things have settled down again.
