### ISSUE TITLE
More capitalization problems

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#32]
With current Propachi installed, this container-title formats wrong:

Ones, D. S., B. M. Wiernik, S. Dilchert and R. M. Klein (2017), ‘Types and definitions of employee green behavior: more than conservation’, in V. Wells, D. Gregory-Smith, and D. Manika (eds), Research Handbook on Employee pro-Environmental Behaviour, Cheltenham, United Kingdom: Edward Elgar.

**Comment by fbennett** [comment]
With which style?

**Comment by bwiernik** [comment]
Seems to happen with any Title Case style. e.g., Chicago (author-date):

Ones, Deniz S., Brenton M. Wiernik, Stephan Dilchert, and Rachael M. Klein. 2017. “Types and Definitions of Employee Green Behavior: More than Conservation.” In Research Handbook on Employee pro-Environmental Behaviour, edited by Victoria Wells, Diana Gregory-Smith, and Danae Manika. Cheltenham, United Kingdom: Edward Elgar.

**Comment by fbennett** [comment]
Great, thanks. Have a fix for it. Working on some other processor changes to accommodate the Z5 migration of Juris-M, will post when I turn the corner on that.

**Comment by fbennett** [comment]
Should be fixed in the latest Propachi now.

**Comment by bwiernik** [comment]
Seems to be fixed.

**Comment by fbennett** [comment]
Yay!
