### ISSUE TITLE
A generic way of suppressing an attribute

### ISSUE THREAD

**Issue by zhaomuzhi** [Juris-M/citeproc-js#33]
I looked at the code and found there is a property "suppress-author" in citationItem that can suppress author attribute. But Is there a generic way to suppress a attribute, e.g. title, publisher and so on? If the answer is no, is there a plan of doing it?

**Comment by fbennett** [comment]
It depends on your requirements. What is the use case?

**Comment by zhaomuzhi** [comment]
Sorry for the late reply. Our current requirement is to suppress the property "title" (for style Chicago Manual 16th edition), but instead of adding another option "suppress-title", is it possible to have a generic way of suppressing any property that could be shown in inline citation, e.g. year of APA style, DOI of Modern Humanities Research Association 3rd edition and so on.

**Comment by dsifford** [comment]
@zhaomuzhi Why not just create and use a custom style matching your requirements using the [CSL style editor](http://editor.citationstyles.org/visualEditor/)?

**Comment by zhaomuzhi** [comment]
@dsifford, off course we can create a custom style and let user select that style when user want to suppress a property, but I don't think that's a scalable solution? Then we have to check every style we support if we need to create custom style, which is not maintainable.

**Comment by dsifford** [comment]
Ah, ok sorry. Misunderstood what you needed. Thought you were speaking of a single one-off requirement.

**Comment by fbennett** [comment]
@zhaomuzhi: There isn't such an option, unfortunately, and it isn't in the roadmap for future development. Your best bet, if you need to do that, would probably be to suppress the undesired fields in the input.
