### ISSUE TITLE
TitleCaser errors out (full disclosure: BBT uses it in possibly inappropriate ways)

### ISSUE THREAD

**Issue by retorquere** [Juris-M/citeproc-js#35]
So, the full disclosure first: BBT uses the titlecaser outside the scope of the citation processor running, so it's fully possible that I'm calling it with an illegitimate state, thereby causing the breakage. I've called the citeproc titlecaser in this way for a long time though, and it has always worked before.

Here's what I'm actually doing:

```
var makeRegExp, state, titleCase;

makeRegExp = function(lst) {
  return new RegExp('(?:(?:[?!:]*\\s+|-|^)(?:' + lst.slice().join('|') + ')(?=[!?:]*\\s+|-|$))', 'g');
};

state = {
  opt: {
    lang: 'en'
  },
  locale: {
    en: {
      opts: {
        'skip-words': CSL.SKIP_WORDS,
        'skip-words-regexp': makeRegExp(CSL.SKIP_WORDS)
      }
    }
  }
};

titleCase = function(text) {
  return CSL.Output.Formatters.title(state, text);
};

console.log(titleCase("/ ' '"));
```

This has always worked splendidly for me, but with this particular string it errors out with

```
var origChar = config.doppel.origStrings[quotePos+1].slice(0, 1);
TypeError: Cannot read property 'slice' of undefined
```
here: https://github.com/Juris-M/citeproc-js/blob/master/citeproc.js#L14984

I've inspected (what I think is ) the relevant state of the function at that point when it breaks, and I see this:

```
CSL: {"config.doppel.origStrings":["","","",""],"quotePos":2,"config.quoteState":[{"opener":" \"","closer":"'","positions":2}],"i":0}
```

While I have zero clues on what doppelString is doing, if I replace

```
var quotePos = config.quoteState[i].pos;
```

with

```
var quotePos = (typeof config.quoteState[i].pos == "number") ? config.quoteState[i].pos : config.quoteState[i].positions;
````

all my tests pass.

(as an aside, it'd be very useful to me if `makeRegExp` were exposed as a method)

**Comment by fbennett** [comment]
Sorry for the long delay in responding. Is it safe to close this, or is the TitleCase-r still causing headaches for you?

**Comment by retorquere** [comment]
I think this must be fixed because I use the titlecaser in my BBT5 work and I've removed the source patches I had in place. I think this can be closed; if new stuff crops up I'll open a new one.

No apologies expected or necessary; I appreciate whatever effort you can put into citeproc.

**Comment by fbennett** [comment]
Good to hear!
