### ISSUE TITLE
Bluebook style has no bibliographies

### ISSUE THREAD

**Issue by MD-Yan** [Juris-M/citeproc-js#36]
We use citeproc-js to format citations and bibliographies. When the bluebook styles are set, it seems no bibliographies are included. From http://csl.mendeley.com/ no layout structures can be found under the bibliography section of bluebook styles (Bluebook Inline, Bluebook Law Review and Bluebook Law Review 2). Is it expected behaviour for these styles?

**Comment by KarlHegbloom** [comment]
Use the jm-indigobook styles instead.

**Comment by MD-Yan** [comment]
What is the official name of jm-indigobook styles? It has to be a recognised style from http://csl.mendeley.com/.

**Comment by KarlHegbloom** [comment]
Oh. It might only work with Juris-M. I don't use Mendeley.

**Comment by rmzelle** [comment]
Hi @MD-Yan, Sebastian already wrote back to you per email about the fact that some CSL styles, like the Bluebook ones, don't have bibliographies.

And the jm-indigobook styles (https://github.com/Juris-M/jm-styles) can't easily be used in Mendeley. @fbennett forked CSL to improve support for legal citations, for use with his fork of Zotero, "Juris-M" (https://juris-m.github.io/). @fbennett's own citeproc-js library that Mendeley uses can handle both standard CSL and these Juris-M styles, but you'd probably have to make quite a few changes to support the latter in Mendeley.

(cc @adam3smith)

**Comment by KarlHegbloom** [comment]
If you use the jm-indigobook-catsort-bib.csl from:


https://github.com/KarlHegbloom/zotero-texmacs-integration/tree/branch-v1.2a-next-wip

... along with Juris-M standalone and TeXmacs, not only will it have a
bibliography, that table of authorities will be grouped in categories with
subheadings, and each bib entry will be followed by a list of pagerefs back
to the points in the document where the citations occur. The README below
the file list on the above linked github page explains installation. It
also contains links to a tutorial PDF and to some demo screencasts hosted
at YouTube.

**Comment by rmzelle** [comment]
(@KarlHegbloom, @MD-Yan is a Mendeley developer, so switching tools is not an option. Since Mendeley already use citeproc-js, they could theoretically support Juris-M styles, but that's not trivial.)

**Comment by fbennett** [comment]
@MD-Yan: Sorry for the long delay in responding from my end.

 As @rmzelle says, the JM Indigo styles probably won't work on the Mendeley platform. As far as I know, the Bluebook itself does not give any guidance on the formatting of bibliographies. It's meant for law reviews and legal briefs, neither of which (ordinarily) have a bibliography in the ordinary sense.

**Comment by fbennett** [comment]
Closing this -- but if anything further needs discussing, feel free to shout.
