### ISSUE TITLE
console.log() lines in 1.1.161

### ISSUE THREAD

**Issue by dstillman** [Juris-M/citeproc-js#40]
1.1.161 introduced a couple stray `console.log()` lines, which broke output for some items in the Zotero beta:

https://github.com/Juris-M/citeproc-js/blob/e0b0b37e01de905dc49592668e2fb6cf975567be/citeproc.js#L9732

(The [commit](https://github.com/Juris-M/citeproc-js/commit/e0b0b37e01de905dc49592668e2fb6cf975567be) also incorrectly calls this release 1.1.166 and left the version number in citeproc.js as 1.1.160.)

**Comment by fbennett** [comment]
Oof. The bundle was prepared, but not checked in for the released. Fixed now in 1.1.162.
