### ISSUE TITLE
Title case for hyphenated words

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#42]
With the current version of propachi installed, the following title (with language="en"):
Closing the scientist–practitioner gap: studies from 2016 with significant practical utility

is rendered as this in Title Case:
Closing the Scientist–practitioner Gap: Studies from 2016 with Significant Practical Utility

In English, the part following the hyphen is generally expected to follow the same capitalization rules as any other word (i.e., treat the hyphen like a space). 

(Am I correct there @adam3smith ?)

**Comment by fbennett** [comment]
That looks like an en-dash. Should the processor normalize that to hyphen, or handle it as if it were a hyphen and pass it through?

**Comment by bwiernik** [comment]
Ah, yes, it is an en-dash.

A quick review of my library suggests that publishers seem to choose an en-dash intentionally, so I would say to handle as a hyphen and pass through.

**Comment by bwiernik** [comment]
That said, in this specific case, the title is intended to mean "the gap between scientists and practitioners", so the traditional interpretation of en-dash as "through" would be appropriate...

**Comment by fbennett** [comment]
Should be fixed now., at tag 1.1.163.

**Comment by bwiernik** [comment]
Actually, this should probably apply as well (even more so) to em-dashes:

Relationship of Core Self-Evaluation Traits—self-Esteem, Generalized Self-Efficacy, Locus of Control, and Emotional Stability—with Job Satisfaction and Job Performance: A Meta-Analysis

**Comment by bwiernik** [comment]
@fbennett

**Comment by fbennett** [comment]
Should be fixed in 1.1.164.

**Comment by bwiernik** [comment]
Thanks!
