### ISSUE TITLE
Multiple uppercase letters for author name

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#43]
I'm encountering this unusual name format:
Osman-Gani || AAhad M.

(Note the double uppercase letter at the start of AAhad.)

Is there a way to prevent the processor from re-formatting this as:
Aahad
?

**Comment by fbennett** [comment]
Um ... should be possible, I think. We would force to lowercase on non-stop-words that are all-caps, but capitalize only the first letter on the others, leaving the stub alone. In transit now, will check on it later. Ping me if you don't hear back in a day.

**Comment by fbennett** [comment]
This has been fixed, at long last. Sorry that it took so long to get to it.

**Comment by fbennett** [comment]
(Will be out in the next release, 1.1.176, when that comes.)

**Comment by bwiernik** [comment]
Thanks!
