### ISSUE TITLE
Wild Idea: Thinking about forking and rewriting this in TypeScript

### ISSUE THREAD

**Issue by dsifford** [Juris-M/citeproc-js#5]
I've come to the conclusion that the only way I'll really be able to understand all of this is if I go through it line-by-line and read it.

That realization led me to the idea of rewriting this in Typescript. 

Benefits:

1. Future-proofing.
2. Optimization + pruning of dead APIs.
3. Readable documentation (possibly using [typedoc](http://typedoc.io/)) so future users can quickly skim to what they need clarification on.
4. Code can be broken into modules (each with their own concern), and then compiled and minified to a single file (better readability).
5. Simultaneously build node packages that can be published and consumed on npm. (I'm aware of [this one](https://www.npmjs.com/package/citeproc), but I think a separate one, specific to React applications would be desired. Or angular. Or `<insert-popular-javascript-framework-here>`)

Would you be interested in teaming up on this? This would obviously be a spare time thing and really wouldn't have any due dates.

Feel free to call me a madman.

**Comment by SamuelMarks** [comment]
+1 I like the idea @dsifford

**Comment by fbennett** [comment]
A clean, robust citeproc implementation in JavaScript would be a great thing for the Web. `citeproc-js` is very serviceable, but it's not at all clean under the hood. A reimplementation effort would be a large, slow-burn, long-term project with slim material rewards, at least in the short term. I would love to see it happen at some point, especially if there were a community of developers working on it. An effort in that direction is well above my skill level, but I would be very happy to kibbitz and offer advice from the sidelines.

**Comment by SamuelMarks** [comment]
Great.

Just wrote up a typing and am debugging it: [citeproc-js.d.ts](https://github.com/SamuelMarks/cust_typings/blob/master/citeproc-js/citeproc-js.d.ts). Somewhere to start from

**Comment by dsifford** [comment]
I'd still potentially be interested helping champion this effort. 

The reason I closed this issue initially is because I realized there are a lot of clever things written in the code that, without @fbennett available to clarify, would be extremely difficult to try and figure out on my own. 

I'm also not familiar with the test assertion library that is used for this project. I've honestly never heard of it. Those two things were the roadblock for me.

**Comment by dsifford** [comment]
Secondarily, I think if time was spent on a project of this size, it would behoove the person(s) who is spending the time on it to relocate variables out of the global scope and switch from an imperative to a functional pattern.

Lots and lots of side effects currently which make it even harder to debug and figure out.

**Comment by dsifford** [comment]
@SamuelMarks I've got some types written that I use when consuming the citeproc library. Those can be found [here](https://github.com/dsifford/academic-bloggers-toolkit/blob/master/types/citeproc.d.ts) and [here](https://github.com/dsifford/academic-bloggers-toolkit/blob/master/types/CSL.d.ts)

**Comment by SamuelMarks** [comment]
>Secondarily, I think if time was spent on a project of this size, it would behoove the person(s) who is/are spending the time on it to relocate variables out of the global scope and switch from an imperative to a functional pattern.
>
>Lots and lots of side effects currently which makes it even harder to debug and figure out.

@dsifford - Why not go further and engineer parser combinators? - Pandoc style so things can be outputted in multiple formats (citation + bibliographical styles)

**Comment by fbennett** [comment]
There is one thing I would add to what I wrote above. Two important extensions over standard CSL are built into citeproc-js:
1. multi-lingual citation support; and
2. support for jurisdiction-specific style modules.

Those two are actually what brought me to Zotero in the first place (and drove me to code Juris-M). I would hope that a reimplementation would cover both, since I think both areas need improved reference management tools pretty desperately. If the aim were to be support only for core CSL, there wouldn't be much call for me to be involved, since there are several others who know that material backwards, and several more talented coders who have tackled it.

**Comment by krassowski** [comment]
Hi @dsifford the types seem no longer available. I understand that you might have deleted them or that they may not be up-to-date, but I wonder if you would consider making them available again, possibly submitting to https://github.com/DefinitelyTyped/DefinitelyTyped?

**Comment by dsifford** [comment]
@krassowski See: https://www.npmjs.com/package/csl-json
