### ISSUE TITLE
page-range-format parsing problem (en-dash vs hyphen)

### ISSUE THREAD

**Issue by tmykkanen** [Juris-M/citeproc-js#60]
There appears to be an issue processing the page-range-format when page ranges are defined using en-dash.

For example:

With page-range-format set to 'chicago',

111-125 in the Zotero pages field produces 111–25 in MS Word (the expected behavior).

However, 111–125 (note the en dash) in the Zotero pages field produces 111–125 in MS Word.

This is true for locators as well (a hyphen processes correctly, an en-dash does not).

I apologize the title is not more descriptive and if this is not the correct place for this issue. I think the problem is somewhere in the citeproc-js code, however.

The issue sounds like the issue here: https://forums.zotero.org/discussion/33793?page=1#Item_13

Which was fixed in 1.0.526. However, using the en_US local, it is still occurring.

**Comment by fbennett** [comment]
I've done a little tweaking of the locator parsing logic, with a little more to come. I'll test for en-dash collapsing when that's out of the way. Simplest thing is probably to normalize to hyphen before dumping the string into the parser.
