### ISSUE TITLE
CSL.Engine.prototype.dateParseArray does not properly handle empty strings

### ISSUE THREAD

**Issue by dsifford** [Juris-M/citeproc-js#62]
https://github.com/Juris-M/citeproc-js/blob/9f7371a6992ad839dd77e854379e1ee8972a0dd5/src/util_date.js#L75-L83

I just noticed this today. Not sure how long this has been an issue.

The gist: If given a `date-parts` array with the following shape, the parser resolves to `NaN` for the empty strings.

```js
const dateparts = [
  '2018',
  '',
  '',
];
```

**My suggestions:**

**Quick fix:**  Instead of just checking to see if the value is `undefined` (which _should not be done using `typeof` to begin with_), consider checking the result of `parseInt`.

So, for example: 

```js

if (!isNaN(parseInt(dp[i][j], 10)) {
// A parsable number
} else {
// Not a parsable number
}

```

**Better fix:** The function itself is extraordinarily complex for what it does. So perhaps consider rewriting it to something a bit simpler? The cyclomatic complexity of this function is way way way way too large. It took me 5 mins just to be able to understand what's going on in the function which is problem and should not happen.

Thanks in advance.

**Comment by fbennett** [comment]
Thanks. Agree this is far too complex. I have too much else on my plate ATM, but would be happy to take a pull request. Will look at a quick fix when time permits, but soon.

**Comment by fbennett** [comment]
Done. I think I'm done apologizing for the code though. The time to catch me on these things was twenty years ago.
