### ISSUE TITLE
'Symbol' is undefined in appendCitationCluster

### ISSUE THREAD

**Issue by dinkom** [Juris-M/citeproc-js#63]
This is quite an edge case so I'm not surprised it isn't covered, but maybe someone can give me a hand.

I am using something like this inside a web worker:
```
const processor = new CSL.Engine(citeprocSys, self.styleXML);
for (let i = 0; i < info.documentCitations.length; i++) {
    // Add citation item from document
    const its = info.documentCitations[i].data;
    const pr = { noteIndex: i + 1 }
    try {
        processor.appendCitationCluster({
            citationItems: its,
            properties: pr
        });
    } catch(err) {
        self.postMessage(err.message);
    }
}
const bib = processor.makeBibliography();
self.postMessage(bib);
```

Works fine, even inside a web worker. However, when put into a web worker inside IE (I believe it's IE11), the catch catches this error: `'Symbol' is undefined`. That is all I get.

To provide more context, this is all happening inside a MS Word add in. Add ins run on different engines on Win and Mac. On Mac, this example works fine. Works online, as well (tried FF and Chrome). However, Word on Windows fails and from what I know, Word uses IE11's engine for add ins.

Web workers do not behave the same on every browser: some functionality is covered, some isn't. Apparently something used in `appendCitationCluster` (or something used in methods called within this method) is most likely not implemented in web workers in IE11. Do you have any idea what it could be? (might be mentioned here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Functions_and_classes_available_to_workers )

**Comment by dsifford** [comment]
@dinkom Symbols are available in workers. It's likely a browser compat issue.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Browser_compatibility

Not sure where `Symbol` is being used though. I'll leave that for others to clarify.

**Comment by dinkom** [comment]
I have found a fix for web workers inside IE11 here: https://github.com/medikoo/es6-symbol/issues/11

I just import this in the worker script:
```
import 'es6-symbol/implement';
import 'es5-ext/array/#/@@iterator/implement';
```

I'm not sure that a lot of your users will stumble upon this particular issue, but maybe this solution helps someone in the future.

**Comment by dsifford** [comment]
@dinkom Are you transpiling this using babel? If so, that might be what's causing the issue.

IIRC, babel converts some loop/iteration constructs using `[Symbol.iterator]`. You might be able to get around this by using a preset specific to your build target.

**Comment by fbennett** [comment]
@dinkom Very good to hear that you have found this fix.

Reading up on `Symbol`, its doesn't seem possible to introduce this object type without an explicit declaration: `var foo = Symbol(bar)`. There is no declaration of `Symbol` anywhere in the code. Are you transpiling to code that throws the error?

**Comment by dinkom** [comment]
Yes, the code is transpiled. However, citeproc-js is imported as is, as a package, isn't it already transpiled? Or is it vanilla js?

@dsifford I had that issue with `for ... of` being converted to using `[Symbol.iterator]` in my own code, but what I described here was after I had changed that and is related to the method I mentioned.

**Comment by dsifford** [comment]
@dinkom To answer your first question, the imported code is one single ~17,000 line file of, for the most part, legacy/backwards compatible vanilla js that is not transpiled.

Specifically, it's this: https://github.com/Juris-M/citeproc-js/blob/master/citeproc_commonjs.js

To comment on your second part: I'm not totally sure. Most likely, there's probably a `for..of` or `for..in` located somewhere in the `appendCitationCluster` method that's causing the issue.

**Comment by fbennett** [comment]
@dinkom For a quick check, does [this dynamic page](http://citeproc-js.readthedocs.io/en/latest/dynamic-editing.html) break for you in the failing browser?

**Comment by dinkom** [comment]
@fbennett just tried it in IE11 and the Styles dropdown is empty.

**Comment by fbennett** [comment]
Thanks for checking. There's something bad in there then. I'll get ahold of IE11 and see if I can figure out what's going awry.

**Comment by dsifford** [comment]
@fbennett The reason why that example doesn't run on IE 11 is because it's using untranspiled es6.

**Comment by fbennett** [comment]
@dsifford Ah, got it. The code that interfaces with the processor there is not mine, and transpiling to es5 is a ways outside my skill box. I can't do anything for it immediately, but I'll keep this on the list. Be nice to figure out where the gremins are for that platform.

**Comment by dsifford** [comment]
Happy to help if needed when I can find some extra spare time. Just let me know what you need.

Same goes to @dinkom. Also, in the meantime, if you can post the stack trace of the error you're getting, I can help brainstorm what might be happening in your application.

**Comment by fbennett** [comment]
@dinkom @dsifford Maybe I'm not quite the luddite after all. I've transpiled the interface module in the page, and it seems to still work. @dinkom Could you check again? If it still fails, that will confirm that will focus suspicion on `citeproc-js` as the likely culprit here.

**Comment by dinkom** [comment]
@fbennett tried it again - works fine now.

@dsifford there is no stack trace. If I don't have the try catch block, the code simply stops executing without any errors. The catch block caught the message and the only method being called inside the try block was the above mentioned method. Building add ins for Word is not very rewarding I'm afraid, especially when you need to debug something. However, the fix with the polyfills is in place and work has moved on.
