### ISSUE TITLE
Suffix field on Layout node does not seem to affect output

### ISSUE THREAD

**Issue by daggmano** [Juris-M/citeproc-js#64]
Changing (or removing) the `suffix` field for the `layout` tag does not seem to have any affect. A period is always placed at the end of the citation.

**Comment by fbennett** [comment]
How are you testing?

**Comment by daggmano** [comment]
Sorry, my fault. I am trying to suppress the layout suffix for a particular type (`post-weblog`) and attempted to do that using a `choose` block within the `citation`, to select one of two `layouts` (one with a suffix, one without).  I just found out that CSL does not allow that, so I'm not sure if what I am trying to do is possible.  Anyway, this ticket can be closed.

**Comment by fbennett** [comment]
In Juris-M, the Zotero variant that I maintain, there is a per-citation option to suppress trailing periods. In mainstream Zotero, I don't think there is a way to accomplish that.
