### ISSUE TITLE
Difference in bibliography HTML

### ISSUE THREAD

**Issue by dinkom** [Juris-M/citeproc-js#65]
This does not feel like a citeproc-js bug, but I'm opening an issue in hope I'll learn what's happening here.

I have a style called American Psychological Association 5th edition. It has a somewhat specific formatting with indentation (every line after the first one is indented). If I try out the style (exact same file) on editor.citationstyles.org, it works perfectly. I've checked the source of the page, it uses citeproc-js package, v1.1.171.

My version of the package is newer, v2.1.204 (from what I understand, that's v1.1.204).

The div wrapper (div right before the div with class `csl-entry`) of the bibliography on citationstyles.org for the mentioned style is:
```
<div class="bibliography-csl-entry" cslid="204" style="padding-left: 2em; text-indent: -2em;">
```

The same div in my app is:
```
<div class="csl-bib-body">
```

This is my code:

```
import CSL from 'citeproc';

// citeprocSys has retrieveLocale for fetching locale and retrieveItem for fetching citation data
const processor = new CSL.Engine(citeprocSys, myStyleXML);

// Load document data in processor
for (let i = 0; i < info.documentCitations.length; i++) {
  // Add citation item from document
  const items = info.documentCitations[i].data;
  const pr = { noteIndex: i + 1 }
  try {
    processor.appendCitationCluster({
      citationItems: items, // already collection of citeproc items
      properties: pr
    });
  } catch(err) {
    // handle error
  }
}

const bib = processor.makeBibliography();
```

`bib[0].bibstart` is , in my case, `<div class="csl-bib-body">`.

I am guessing I am doing something wrong since the style and citeproc-js obviously work on citationstyles.org editor. Every other part of bib for this style (such as journal name in italics) is correct in my app. 
Any ideas what's happening here?

**Comment by fbennett** [comment]
You are right that `v2.1.204` in the npm distro corresponds to the `v1.1.204` release.

The earlier `v1.1.171` version of `citeproc-js` also delivered `csl-bib-body` as the class of that object. The editor at `editor.citationstyle.org` must be doing post-processing on the output from the processor. The hanging indent is produces by the explicit styling that the editor apparently also applies:

    style="padding-left: 2em; text-indent: -2em;"

The processor doesn't attempt to force the hanging indent in the HTML itself; it reports the indent config in a separate segment of the data it returns. You can force that styling in your rendered pages with CSS:

    .csl-bib-body {
        padding-left: 2em;
        text-indent: -2em;
    }

That gets you a one-size-fits-all solution (i.e. always to set a hanging indent). If you need dynamic response to accommodate different styles, it gets more complicated. The approach would depend on your server environment and your coding preferences.

**Comment by dinkom** [comment]
Ok, thanks, understood. I will have to do it dynamically, but at least I have the hanging indent in `bib[0].hangingindent` so if I see it, I'll add the style manually, not a big issue.
I was concerned that I was using the library in a wrong way, but since this is due to post-processing, it's clear what I need to do.
