### ISSUE TITLE
Correct object format for Authors

### ISSUE THREAD

**Issue by dinkom** [Juris-M/citeproc-js#66]
I have the following format for Authors as a part of the data I am giving to the CSL processor:

```
[
  {
    first: "FirstName",
    last: "LastName",
    initial: "MiddleName",
    type: "author"
  }
  ...
]
```

This does not produce any errors, but I am doubtful regarding the `initial` field. In my UI, that is actually the middle name. It does not get displayed inside the bibliography HTML after calling `makeBibliography()`, while the rest (first and last name) get displayed correctly. If the same style is applied inside the citationstyles.org editor, everything works fine.

So, for instance, instead of:
```
Miller, Emily B., Stephen, Joseph H. ...
```

I get:
```
Miller, Emily, Stephen, Joseph ...
```

All other data is correctly shown. I am having trouble finding the mention of a middle name (or initial) inside the style.csl file itself (style is American Political Science Association).
My guess is that my Authors object is not formatted right, but I couldn't find the correct way to format it in the docs (I also tried naming the `initial` field as `middle`, just a guess, but it's not working). Is this the case, that my Authors object is formatted the wrong way or is this the case of some post-processing outside the CSL processor?

**Comment by fbennett** [comment]
If you have the data in separate fields, you can just concatenate the "first" and "initial" values, delimiting with a space, and put the combined value on the "given" key when shipping to the processor.

**Comment by dinkom** [comment]
If I do as you suggested, the middle name gets displayed next to the first name. The only thing remaining is to display the middle name in the form of an initial, but I'm not sure citeproc is to blame here: I'm guessing the middle name needs to be edited on my end to be in a proper form. Unless I'm mistaken and there is a case in which citeproc would take an input `FirstName MiddleName` and turn it into `FirstName M.`?

**Comment by fbennett** [comment]
Got it. CSL isn't able to discriminate between the first and middle names when converting to initials. It's either all ("F. M.") or nothing ("Firstname Middlename"). If the data has pre-initialized the middle name, it will come through as "Firstname M." when rendering the full name, but the processor can't apply the initialization to the middle name only by itself.

Pushing the spec in that direction would be hard, since names come in many flavors across different languages, and the concept of a "middle" name is not universal.

**Comment by dinkom** [comment]
I understand, makes sense. Thank you again for a quick response and your help!
