### ISSUE TITLE
move testsuite to Node.js / JavaScript

### ISSUE THREAD

**Issue by DanielRuf** [Juris-M/citeproc-js#68]
It would be better to move the tests to a npm script and use Travis CI for running them on each commit and PR.

It is not clear to new contributors how the testsuite can be run.

Also the commands to run all tests and required steps are not clear for Node.js / JavaScript developers.

**Comment by fbennett** [comment]
I would be happy to look at a PR that reimplements the test runner in node.js, and to advise anyone that wants to take it on, but I don't have time to do the work, unfortunately.

CI is great for fast-moving projects that need to reconcile multiple incoming contributions. It is not a high priority for `citeproc-js`, which is now pretty static apart from very occasional bugfixes. The linked documentation explains how to set up and run the tests locally.

Many things could be improved in the processor, although it is a hardy thing that does do what is asked of it. I am autodidact in JavaScript, and (I am told) the [expletive deleted] code is not pretty. The best gift to the future would be a clean reimplementation, perhaps in another, faster language. That would require dedication of significant resources from some quarter, but it would be the best route to long-long-term maintainability.

**Comment by DanielRuf** [comment]
I will try to help with this and keep an eye on further improvements (eg Chakracore, v8, ...).

Unfortunately I have never used Python before and the docs are a bit unclear to me (have to study and reread the file to fully understand what it does and how it works in the current implementation).
