### ISSUE TITLE
use version from package.json

### ISSUE THREAD

**Issue by DanielRuf** [Juris-M/citeproc-js#69]
https://github.com/Juris-M/citeproc-js/commit/456ad4179e6270ad567562af9097b44975508f5f is tedious and we could require package.json and use the version property in the files and include that in the build process.

Also it is not clear to me why there is another major version in package.json.

**Comment by fbennett** [comment]
The numbering anomaly is an artifact of history. When I added the `npm` distribution to the release chain, multiple `citeproc-js` bundles had been published there, and the one that I took over for this purpose was at version `2`.

I am sorry that you find the "Bump version ..." checkins tedious.

**Comment by DanielRuf** [comment]
> multiple citeproc-js bundles had been published there, and the one that I took over for this purpose was at version 2

Oh, didn't know this. Unfortunately (or fortunately securitywise) old releases can not be overwritten.

Not sure if `semantic-release` or any other solution would be helpful at all.

Possibly we could improve the release task somehow.

I'm closing this issue as we have to find another solution and I am now aware why there is this version mismatch. Thanks for the explanation.
