### ISSUE TITLE
Q: Reaching out

### ISSUE THREAD

**Issue by tbell511** [Juris-M/citeproc-js#73]
Hello! 
I have been researching citationstyles.org and have been looking into citeproc-js.  I have a list of questions regarding the processor; would it be possible to go over them with someone instead of posting them here?  

I am from Formatically.com, and I am in the process of transitioning our citation tool (formatically.com/citation-tool) to utilize CSL. 

Thanks!
Tyler Bell

**Comment by dsifford** [comment]
@formatically If you have financial support of formatically behind you, please consider rewriting the processor using modern, tree-shakable javascript. The current implementation is _highly_ costly at runtime being that you're forced to import all 17k lines of code, even if you only require just a small fraction of it.

I've been wanting to do that for the better part of the last 2 years or more and I haven't been able to given the fact that I have no financial support for doing so.

That said, I'm happy to answer some questions if @fbennett isn't able to.

**Comment by fbennett** [comment]
Tyler @formatically As @dsifford says, I would not be the person to recast the processor.

Please free to contact me directly on bennett@law.nagoya-u.ac.jp if you have questions about the existing code.

**Comment by formatically** [comment]
Thank you both for offering to answer questions. 
@dsifford Currently Formatically's financial support is tied up in our main product.  Perhaps we could fund an updated implementation down the road.

**Comment by formatically** [comment]
Hi @dsifford, I have a question for you.  I would like to maintain the order in which the citations were created.  Currently, makeBibliography() alphabetizes them like it should.  Do you know of any practical ways to make new citations always appear on the top?  I am assuming I would be using something totally different than makeBibliography.  

Thanks!

**Comment by dsifford** [comment]
@formatically Citation order is dictated by the CSL style. So, you might want to check [here](http://editor.citationstyles.org/visualEditor/) to see if there's one that fits your needs. If not, you'll have to make it yourself.

As for your second question: Poke around in [this project](https://github.com/dsifford/academic-bloggers-toolkit) for higher level implementation strategy ideas. There's many such ways to go about what you're describing, so really it just boils down to whatever works best for your implementation.

**Comment by dsifford** [comment]
I do not, but the project I linked to you has an extremely heavy ingeration to citeproc so that should be enough to get you started.

Most of the stuff I have heavily documented as well so you should be able to see pretty clearly what's going on

**Comment by formatically** [comment]
Awesome, thank you.  I will start looking into it.

**Comment by formatically** [comment]
@dsifford Can I get a link to a webpage that is using your academic toolkit code? Thanks

**Comment by dsifford** [comment]
Here's a few that I know of...

https://www.aliem.com/

https://emcrit.org/

http://stemlynsblog.org/

https://canadiem.org/

**Comment by formatically** [comment]
Thank you

**Comment by formatically** [comment]
@dsifford @fbennett 
No matter the style, I cannot get the "accessed" field to appear in citations.  Is there something special that I need to do with cite-proc for it to include an accessed date? 

The style I am using is Modern Language Association 8th Edition (CSL File here: http://www.zotero.org/styles/modern-language-association)  It's the exact same style file that zbib is using, and the accessed date works fine over there.  

So I am assuming I am doing something wrong... Any thoughts on what could be causing this? 

The CSL Object I am trying is:
```
{
URL: 'http://example.com',
id: 'uniqueid',
accessed: '07/13/2018',
title: 'My Title',
type: 'webpage'
}
```

which outputs: `My Title. http://example.com.`

I am expecting: `My Title. http://example.com. Accessed 13 July 2018.`

**Comment by formatically** [comment]
bump ^^

**Comment by fbennett** [comment]
Sorry for the delay. It's the date form. Here's the <a href="https://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#date-fields">manual description</a>. The array entry format is best. It's ugly and cumbersome, but it's the most stable form, since citeproc-js does not yet incorporate a standard date parser. (There has been talk of moving toward EDTF in the CSL spec, but we're not there yet.)
