### ISSUE TITLE
Extract subtitles after em-dash as well as colon

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#74]
APA and other styles with similar uppercase-subtitle rules recommend that subtitles be capitalized after both the colon (currently supported by citeproc-js) and the em-dash `—`. citeproc-js does not currently uppercase subtitles after an em-dash (whether or not spaces are included before/after the dash. I think this should be adjusted.

Other em-dash-like constructions that sometimes imported from databases (though ideally users would correct these to em dashes in their data:
`--`
`-- `
` -- `
` - `

citeproc-js also does not capitalize subtitles after sentence-ending punctuation marks (`.` `?` `!`). While generally words in titles after these marks would be stored in uppercase, should citeproc-js be more robust about uppercasing them when uppercase.subtitles in enabled?

**Comment by bwiernik** [comment]
@fbennett I think we discussed this at some point a few years ago.

**Comment by fbennett** [comment]
We should fix this indeed. There will be a bunch of cases to cover. This would be another good candidate for settling test coverage before changing the implementation, if that's alright.

**Comment by fbennett** [comment]
Further to https://github.com/zotero/zotero/issues/1681, extending the set of break characters should be an easy step. I'm less certain about breaking on punctuation alone. There would be false positives, which by itself isn't necessarily a problem, but I'm not sure what you would do to override them when they crop up.

**Comment by fbennett** [comment]
Oh, wait. There *is* a way to loosen this up while avoiding false positives. We can split by default on the first split-char, but where the short title matches exactly to a spot immediately before a (later) split-char, we prefer that for the split. That provides a mechanism for override, which was my only objection.

**Comment by bwiernik** [comment]
That sounds reasonable. I will look for some counter examples where that wouldn’t work. 

For splitting just on punctuation, i think including the space after colon and fullstop is necessary.

**Comment by bwiernik** [comment]
Is it feasible to address titles with multiple subtitles?

For example:
Comment on “Pigs can fly: A meta-analysis”—Authors’ response

Here “A” and “Authors’” should be capitalized in APA-case but not in Vancouver sentence case.

**Comment by fbennett** [comment]
That was the kind of thing I had in mind. The data would need to set 'Comment on “Pigs can fly: A meta-analysis”' as short title, and that would rix it.

**Comment by bwiernik** [comment]
What if the data were stored as:
Comment on “Pigs can fly: a meta-analysis”—authors’ response

Which should return—

Vancouver:
Comment on “Pigs can fly: a meta-analysis”—authors’ response

APA:
Comment on “Pigs can fly: A meta-analysis”—Authors’ response

(Note the 2 subtitle capitalizations.)

**Comment by fbennett** [comment]
The quote is a quote though. Shouldn't that be verbatim to the original?

**Comment by fbennett** [comment]
Actually, I think we can have it both ways. I have code in place now that can override a string-parsed split, when there is a good match immediately followed by a split-point. The override could be applied in two ways:
1. Refuse to apply caps if there are multiple splits, and use the override to choose which one is real; or
2. Apply caps to all splits *unless* there is a matching override, in which case recognize one split only.

In current testing, I have implemented it as (1), but your case above would want (2). Both are safe enough, I think, so I can just adjust the logic and maybe we're home free.

For another question, should typographically ugly ersatz em-dashes and space-prefixed colons be cleaned up in output, or should we leave those as an exercise for the user?

**Comment by fbennett** [comment]
Code is in place in a branch of `citeproc-js`, ready for merge. Check these tests and see what you think.
* [abbrevs_TitleMainTitleSub](https://github.com/Juris-M/citeproc-js/blob/master-fix-title-splits/fixtures/local/abbrevs_TitleMainTitleSub.txt)
* [form_ContainerTitleShortWithTitleSubSupport](https://github.com/Juris-M/citeproc-js/blob/master-fix-title-splits/fixtures/local/form_ContainerTitleShortWithTitleSubSupport.txt)

**Comment by bwiernik** [comment]
1) Eraatz em-dashes (three hyphens yes, not sure about other combinations) should probably be cleaned. 

2) Space before colon depends on language. It’s correct in French. Could clean based locale or leave to the user. 

3) For the first test, also:
Third main title—third subtitle

Third main title. Third subtitle

4) What about spaces around em dash?

5)

**Comment by bwiernik** [comment]
For the colon question, how is localization of punctuation handled more generally? Could that be cleaned here and then fixed during localization?

**Comment by fbennett** [comment]
We don't touch content, apart from quotes and closing-quote/punctuation swaps. In this specific case, we could do a language-sensitive adjustment, but there are a bunch of unknowns: uniformity within fr; uniformity within fr-like domains; treatment when fr works are cited in a non-fr style; treatment when non-fr works are cited in an fr style; treatment when an fr title is embedded in a non-fr title. Different users/editors could have different preferences in some of those cases, and if any raise a red flag, we would be stuck.

Any thoughts? I'm not sure what the best treatment would be.

**Comment by bwiernik** [comment]
Hmm. Not sure what the best alternative is. @adam3smith thoughts?

**Comment by bwiernik** [comment]
Looking into it some more, in French a narrow no-break space is always used to precede a colon (as well as ; ? and !). I think cleaning up spaces when the bibliography and item locales are not French is fine. 

See also this related discussion https://forums.zotero.org/discussion/73078/non-breaking-space-issue

For punctuation on than —, I’m thinking a following space should be obligatory. 

So “The role of C4:aB binding” should not be trasformed. Same for . ! and ?

Is there a test for that?

**Comment by fbennett** [comment]
Thanks for checking those details. I'll do a trawl of the code tomorrow, to see if there are any tweaks for French in there that I had forgotten. On terminal punctuation, it is set up to require trailing space, but you're right, the tests need to be filled out, to show the "envelope," with things that don't parse as well as things that do - and French examples should be in there as well.

**Comment by denismaier** [comment]
Wouldn't it make sense to discuss this together with the broader question if punctuation can be localized in some way or the other?

**Comment by fbennett** [comment]
@bwiernik Take a look at these:
https://github.com/Juris-M/citeproc-js/blob/master-fix-title-splits/fixtures/local/form_ContainerTitleShortWithTitleSubSupport.txt
https://github.com/Juris-M/citeproc-js/blob/master-fix-title-splits/fixtures/local/form_ContainerTitleShortWithTitleSubSupportFrench.txt

@denismaier Ideally that would be so, but adjustments on that front will depend on changes to the CSL Specification. The changes here are just temporary hackery to keep things more or less afloat for one language subdomain that has a bunch of users.

**Comment by fbennett** [comment]
@bwiernik Ping (when you have time)

**Comment by bwiernik** [comment]
Will try to look this weekend. Deadlines.

**Comment by bwiernik** [comment]
Okay, these look good behavior-wise. Some changes to the test text for clarity might be useful

For the French tests, the title of the "immediate" tests (e.g., `Title input with immediate colon : Should start with uppercase`) should state `Should normalized and start with uppercase` because a space is added to these, unlike in English.

For French, the `narrow-no-break-space-` tests should *not* state `normalize`, as the spacing is not changed.

In both English and French, `Title input with space-em-dash-space` should state `Should normalize and start with uppercase`

I don't understand what the `Title input ending in single letter : Should start with uppercase if title-short matches main title` test is testing.

**Comment by bwiernik** [comment]
Need any more input from me?

**Comment by fbennett** [comment]
I think it's all set - I've just be tied down by another project.

**Comment by fbennett** [comment]
Descriptive text changes applied.
