### ISSUE TITLE
Open-ended date ranges

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#75]
Old versions of the citeproc-js docs indicated support for open-ended date ranges, but the current version does not, and these methods no longer work:
https://web.archive.org/web/20150911220234/http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#dates

Is there any way currently to pass open-ended date ranges to citeproc-js? If not, could this feature be restored somehow?

(More generally, what is the status on thoughts for better support of EDTF generally since this was last discussed here? https://github.com/citation-style-language/schema/issues/130 

Perhaps even just small additions, like support of 21, etc. for seasons and `19uu` notation for uncertain digits? https://github.com/inukshuk/edtf.js​ and https://github.com/nicompte/edtfy both appear quite robust at this point.)

(BBT has some expanded date parsing relative to citeproc-js, including more indicators for circa and uncertain digits, but doesn't seem to support open-ended date ranges either.)

@fbennett @rmzelle @adam3smith

**Comment by fbennett** [comment]
There is a [test for this](https://github.com/citation-style-language/test-suite/blob/master/processor-tests/humans/date_TextFormYeardateYearRangeOpen.txt) in the CSL test suite, and ``citeproc-js`` still passes it. The calling application would need to be teased into supplying data in the very non-standard format read by the processor, though. The  proper solution will be to embed an EDTF library to parse dates properly. If anyone wanted to take that on, I could advise on who to tie it into the existing code base.
