### ISSUE TITLE
Illustrator not being parsed or rendered correctly

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#76]
https://forums.zotero.org/discussion/72782/citeproc-js-bug-illustrator-in-extra#latest

I'm encountering a bunch of issues with the `illustrator` creator type.

First, if I try to enter an Illustrator in Extra following the standard citeproc-js format:
Illustrator: Smith || John C.

The name parser doesn't work like it does for other creator types. Instead, both name parts get treated as family names. For example, the above gets rendered in iso690-author-date-sk.csl, which formats names as FAMILY, Given A., as:
JOHN C., SMITH

(The same happens if I use the {:illustrator: } syntax.)

Other creator types entered into Extra work correctly.

Second, if `<names variable="illustrator">` is used in substitute without its own `<name/>` element, it doesn't render at all. 

This works:
```
<names variable="author" delimiter=", ">
          <name form="short" and="symbol" delimiter=", " initialize-with=". "/>
          <substitute>
            <names variable="illustrator">
              <name form="short" and="symbol" delimiter=", " initialize-with=". "/>
            </names>
          </substitute>
</names>
```

This does not:
```
<names variable="author" delimiter=", ">
          <name form="short" and="symbol" delimiter=", " initialize-with=". "/>
          <substitute>
            <names variable="illustrator"/>
          </substitute>
</names>
```

**Comment by fbennett** [comment]
The =illustrator= variable was missing from the list of name variables. It should be working correctly from tag 1.1.210, which just went up.
