### ISSUE TITLE
Titlecaser capitalizes sole letter at end

### ISSUE THREAD

**Issue by retorquere** [Juris-M/citeproc-js#78]
`O7-x` capitalizes to `O7-X`, where `O7-x test` capitalizes to `O7-x Test`

**Comment by retorquere** [comment]
So titlecasing is one of those [surprisingly difficult things](http://blog.apastyle.org/apastyle/2012/03/title-case-and-sentence-case-capitalization-in-apa-style.html), but short words should apparently not be capitalized (and both `O7` and `x` are shorter than 4 letters, so short for this purpose), but then [sometimes short words *are* capitalized](http://blog.apastyle.org/apastyle/2012/03/title-case-and-sentence-case-capitalization-in-apa-style.html#comment-6a01157041f4e3970b01b7c8fca4ac970b). Great fun.

**Comment by fbennett** [comment]
CSL doesn't attempt do style-specific title-casing. We're guided by Chicago mostly, and I think it's CMS rules that require capitalization of a preposition at the end of a title. The glitch here is caused by a condition that bypasses a skip-list check of prepositions *and* the word-length constraint (oops).

So ... I guess what we want here is to additionally capitalize if the last word has length greater than one AND matches a word in the stop-list. Should now be covered by [88f672e5](https://github.com/Juris-M/citeproc-js/commit/88f672e595c7c93f26b3fcacd300cb406e6772a1).

**Comment by retorquere** [comment]
I currently use the citeproc that ships with Zotero, so I'll get this in due time.

What's your opinion on title-casing sub/subscript text? I have (as of yesterday) workarounds in place that treat sup/sub like as nocase.

**Comment by retorquere** [comment]
What does `doppel` and `wordDoppel` mean in the titlecaser BTW? I've tried to follow how the titlecaser does its work but I'm stumped.

**Comment by fbennett** [comment]
Um ... yes, sub/super should imply `nocase`, shouldn't it. Will try to fix that. The `doppel` stuff separates text and cruft (mostly tags) into separate arrays, to make it easier to step through the text elements.

**Comment by retorquere** [comment]
I just keep a [parse tree](https://github.com/retorquere/zotero-better-bibtex/blob/1037/content/markupparser.ts) and step through that. I use a bit of trickery to use the CSL titlecaser; perhaps no longer required with these latest fixes but there used to be cases that the CSL titlecase didn't handle well (but those were long ago, I reported those when you still used bitbucket). The process that I have now does:

1. use an HTML(ish) parser to parse the input into a tree of nodes, remembering in the tree where the plaintext chunks live in the source string<sup>1</sup>
2. re-assemble a plaintext string that skips all the markup
3. pass that string to the CSL titlecaser
4. walk the tree again and replace those text chunks in the AST that were not marked `nocase` (and now also `sup` or `sub`) with the corresponding part in the titlecased string
5. profit

So for 

> `reading <span class="nocase">HLA</span> Hart's: <i>the concept of law</i>`

the title caser only sees

> `reading HLA Hart's: the concept of law`

and in step 4 I only replace 

* `reading `,
* ` Hart's: `, and
* `the concept of law`

with whatever the titlecaser made of those in the result string; the rest I ignore. It's convoluted but in my experience the titlecaser worked best if it didn't have to deal with markup. Given that I already did only partial replacements, adding `sub`/`sup` was easy to do (just ignore those bits in the result string).

Once the `sup`/`sub` lands in Zotero I'll set up a build to see if this trickery is no longer required.

----

<sup>1</sup> this step actually does a little more, recognizing words with caps in them and marking them nocase, but that isn't relevant here I think.

**Comment by fbennett** [comment]
That's pretty much what the title-caser in citeproc-js is meant to do. The code has been through a couple of iterations since BitBucket days, so the old edge cases may process correctly now (and, of course, new ones may break...).

**Comment by fbennett** [comment]
I've set up to suppress case-changes inside the `sub`, `sub` and `sc` tags. The last one was set to suppress in the legacy `span class="small-caps"` form, but not in `sc`. Suppression seems right, since that would mostly be used in bio/chemistry titles. Commit: 30ceaf50a0ef86517a9a8cd46362e450133c7f91

**Comment by retorquere** [comment]
I'll give that a go once it makes its way into Zotero. I'd be happy to drop some of the complexity of BBT.
