### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by burs14** [Juris-M/citeproc-js#79]
I have been reading into the licenses, and am honestly confused as to what they imply. I was wondering if I could clarify what the implications are for the AGPL/CPAL licenses for this library.

I want to use this library on the client side of a web application I am writing, without any modifications to the source code. I intend on simply calling this library from my own code. 

In particular, my concerns are as follows:
- Do the licenses require that the source code for my entire application be released if I use this library? 
- As part of serving the web application, typically there is a minification process to reduce the file size 
  - Does this count as modifying the source code?
  - If so, am I required to release the source code for my entire application, or simply the processed version of the library code?

**Comment by fbennett** [comment]
The main concern is that people not embed the processor and styles in an application, and then pretend to the world that its formatting capabilities are their own product.

If you embed the processor in a project, and the source code for the project is not made publicly available, you need to indicate to users that the project uses CSL technology. The simplest way to do that is by linking to the CSL site, or to the citeproc-js source code, in a place where people will find it. The citeproc-js licenses are not meant to somehow infect other code.
