### ISSUE TITLE
Q: Modifying parsed templates

### ISSUE THREAD

**Issue by larsgw** [Juris-M/citeproc-js#80]
Are there any problems with adding `cs:text` elements with only a `value` attribute to the parsed style template to mark the end and start of an entry in the output? Are there side-effects to sorting, substitution, etc. maybe? And is it enough to add the appropriate elements to `CSL.Engine#cslXml.dataObj`, or would I have to change it somewhere else as well?

**Comment by fbennett** [comment]
There is probably a safer route, depending on the requirements. By "entry" do you mean an item, or a field entry? What kind of marker are you wanting to splice in?

**Comment by larsgw** [comment]
Yeah, this is definitely an X/Y problem. An example: appending an Altmetric badge after each bibliography item. I do this now by 'parsing' the output HTML with RegExp, but I'd like it to work for arbitrary formats, and without needing RegExp to parse HTML. Since you can't insert HTML (and therefore the badge) directly in the template, AFAIK, I though maybe something like this would work:

template:

```xml
<bibliography>
  <text value="RANDOM_STRING">
  ...
  <text value="RANDOM_STRING">
</bibliography>
```

citeproc-js output:

```html
<div ...>RANDOM_STRING ... RANDOM_STRING</div>
```

processed output:

```html
<div ...>PREFIX ... POSTFIX</div>
```

Of course, finding a `RANDOM_STRING` that would work and couldn't interfere with e.g. the `title` is probably theoretically impossible (although practically it might work), and it isn't a pretty solution either way.

**Comment by fbennett** [comment]
Would the `itemID` (or a derivative) work for your RANDOM_STRING identifier?

**Comment by larsgw** [comment]
Sure, but that ID might be the DOI in some cases (I should probably change that)

**Comment by larsgw** [comment]
But that would be for citation entries then? Because `sys.embedBibliographyEntry` seems to only append, after the entry itself.

**Comment by fbennett** [comment]
So you need a wrapper around bibliography blocks? (Sorry, I'm not yet clear
on the overall aim.)

**Comment by larsgw** [comment]
Citation.js provides an option to prepend and append content inside bibliography entries, for example to add altmetric badges to each entry. However, currently this option works by determining what the inside of the entry is with regex. I'd rather have something that always works. As for the alternative solution, I think creating a proxy for `@bibliography/entry` would work.

Thanks for the help, and my apologies for the confusion.
