### ISSUE TITLE
Default Locale

### ISSUE THREAD

**Issue by mshd** [Juris-M/citeproc-js#81]
I'm using Citeproc in NodeJS ("citeproc-js-node")

Problem with default-locale:
Won't run if default-locale is specified in CSL file by smt. other than "en-US" (but it can be empty)
Error:
> citeproc/citeproc_commonjs.js:1909
        throw "citeproc-js error: unable to parse CSL style or locale object";

My fix is to change the CSL files 
` styleString.replace(/<([^>]*)(\sdefault-locale=\".+?\"(\s|))(.*?)>/,'<$1$3>') `
remove default locale from all CSL files
and then load the Engine
`  var engine = sys.newEngine(styleString)`

However there must be another solution to the problem.

**Comment by fbennett** [comment]
The processor needs to have access to the relevant locale file, via the [retrieveLocale](https://citeproc-js.readthedocs.io/en/latest/running.html?highlight=retrieveLocale) method set on the ``sys`` object (documentation is under the link).
