### ISSUE TITLE
Version undefined

### ISSUE THREAD

**Issue by mshd** [Juris-M/citeproc-js#82]
There seems to be a problem when the version is undefined. It throws errors for several CSL files

> if ( this.opt.version.slice(0,4) === "1.1m") {
                          ^
TypeError: Cannot read property 'slice' of undefined

I modified line 2654 to 
`if (this.opt.version != undefined && this.opt.version.length > 3 && this.opt.version.slice(0,4) === "1.1m") `

After changing it worked

**Comment by fbennett** [comment]
The version attribute is [required on the cs:style node](https://docs.citationstyles.org/en/1.0.1/specification.html?highlight=version#the-root-element-cs-style). The processor could handle the error more gracefully, but it should indeed throw an error if it is absent.
