### ISSUE TITLE
Various questions about CSL / Citeproc

### ISSUE THREAD

**Issue by coryschires** [Juris-M/citeproc-js#83]
Hi! I'm sorta new to the world of CSL / Citeproc. But I am enjoying learning about it. As a specification, it's impressively thorough especially given the huge variety of citations styles in the wild. 

Anyway, I have a few questions regarding CSL / Citeproc, so hopefully this is the right place to do that.

### 1) Does CSL dictate the title of the references page / section?
For example, [MLA recommends "Works Cited"](https://owl.purdue.edu/owl/research_and_citation/mla_style/mla_formatting_and_style_guide/mla_works_cited_page_basic_format.html) whereas [APA recommends "References"](https://libanswers.dominican.edu/friendly.php?slug=faq/8000). This leads me to suspect that different citations styles may have different opinions about the exact title of the citations page / section. 

But I couldn't find anything in the CSL docs or Citeproc-JS regarding this topic. Is this left to the word processor / publisher? Or is this something that CSL enforces?

### 2) Does CSL dictate how to format footnotes (as distinct from in-text cites)
[Based on reading the "Note Styles" section of the CSL primer](http://docs.citationstyles.org/en/stable/primer.html#note-styles), it seems that CSL has no opinion about footnotes:

> CSL styles do not control which number formats or symbols are used for the markers, which is left to the word processor. 

Assuming that's correct, how do publishers generally handle footnotes in citation styles, like AMA, where in-text cites are numbered. Wouldn't this create a situation where, say, `[1]` points to a citation but later another `[1]` (confusingly) points to a footnote. Maybe they disambiguate by using symbols (e.g. `*`, `†`, etc) rather than numbers for footnotes? 

### 3) Is there an open-source CSL-JSON validator?
I see that there's a [validator for CSL XML files](https://validator.citationstyles.org). But I'm looking for something a little different. I want to validate the CSL-JSON for a given citation. 

Here's my use case. I have a web app with a `<textarea>` where users can edit the CSL-JSON for a given citation. I would like to have a client-side validation to ensure the JSON includes required keys (e.g. `id`, `type`) as well as the available fields for each item type (e.g. `author`, `container-title`, etc). As I envision it, the exact validation rules would follow the [rules outlined by Aurimas Vinckevicius](https://aurimasv.github.io/z2csl/typeMap.xml).

So my questions here:

1. As far as you know, has someone already built this? If so, I don't want to reinvent the wheel.
2. If this doesn't already exist, I'll probably write an open source library – assuming this idea / use case makes sense?

Thanks so much for making and maintaining the project! Understanding citation styles is much harder than I expected, and it's been a huge help have CSL / Citeproc as a solid foundation.

**Comment by rmzelle** [comment]
> 1) Does CSL dictate the title of the references page / section?

No. CSL styles don't generate this header. They have no idea it exists.

> 2) Does CSL dictate how to format footnotes (as distinct from in-text cites)

CSL only dictates what goes into the footnote, and doesn't describe the symbol or number connecting the footnote to the body text. (this is different from e.g. author-date or numeric in-text CSL styles).

It's probably rare to combine a numeric in-text citation format with footnotes, but yes, if you had both you would use a non-numeric system for the footnote markers, or use a different number formatting (e.g. superscript vs. brackets).

> 3) Is there an open-source CSL-JSON validator?

No, there isn't as far as I know. Understand that Aurimas' mapping describes the current setup in Zotero, which isn't necessarily right or wrong, although most CSL styles in the central repository have been written based on this system.

There is a JSON schema at https://github.com/citation-style-language/schema for CSL JSON, but it doesn't put any restrictions on which fields are available to which item types. It was also written to validate the CSL JSON format as used by citeproc-js (which was the first to introduce CSL JSON), and is descriptive, and not necessarily prescriptive.

(and yes, getting familiar with CSL takes a while. It's complicated, as is the world of citations it tries to model. You've seen http://docs.citationstyles.org/en/stable/primer.html ?)

**Comment by coryschires** [comment]
Thanks for following up! Very helpful. 

I am closing this issue as I think my questions have been answered.

Thanks again!

**Comment by rmzelle** [comment]
Great. You're welcome!
