### ISSUE TITLE
Bug when author and the date-parts are equivalent 

### ISSUE THREAD

**Issue by mshd** [Juris-M/citeproc-js#86]
I found a bug, which is been bugging me for the last days, because the script would not give an error but just got stuck. I'm using debian, nodejs citeproc-js. 
It seems that **if** the **author and the date-parts value is the same, the script doesn't work** for hundreds of CSL styles. In this case the Author is just " " but it's the same if you put another name in it.
The script gets stuck when executing `  engine.updateItems(citation_keys); `

Example: (for reasons of simplicity I removed part of the json)
```
[
  {
    "id": 0,
    "author": [
      {
        "given": " ",
        "family": " ",
      }
    ],
    "container-title": "Tijdschrift voor praktijkondersteuning",
    "issued": {
      "date-parts": [
        [
          2006,
          8
        ]
      ]
    },
    "URL": "http://dx.doi.org/10.1007/bf03074904",
    "ISSN": "1872-4078",
  },
  {
    "id": 1,
    "author": [
      {
        "given": " ",
        "family": " ",
      }
    ],
    "container-title": "Huisarts en Wetenschap",
    "issued": {
      "date-parts": [
        [
          2006,
          8
        ]
      ]
    },
    "URL": "http://dx.doi.org/10.1007/bf03084836",
    "ISSN": "0018-7070",
  }
]
```

**Comment by fbennett** [comment]
I've built a test fixture from your data. It runs without error in a simple snippet of CSL. Can you point at a specific style that hangs with that input?

**Comment by mshd** [comment]
Sure, the first CSL style for example: academy-of-management-review.csl

**Comment by fbennett** [comment]
The input works fine in the test runner. I get these results for ``citation``:
```
>>[0] (Brown, 2006a, 2006b)
```
And these results for ``bibliography``:
```
<div class="csl-bib-body">
  <div class="csl-entry">Brown, J. 2006a, August. <b><i>Tijdschrift voor praktijkondersteuning</i></b>. http://dx.doi.org/10.1007/bf03074904.</div>
  <div class="csl-entry">Brown, J. 2006b, August. <b><i>Huisarts en Wetenschap</i></b>. http://dx.doi.org/10.1007/bf03084836.</div>
</div>
```
In what environment are you running the processor?
