### ISSUE TITLE
Support integration into Scrivener

### ISSUE THREAD

**Issue by iandol** [Juris-M/citeproc-js#89]
This is not an issue with citeproc-js, but Keith, the developer of the excellent writing app Scrivener, is contemplating the possibility of how he may integrate citeproc-js into Scrivener:

http://literatureandlatte.com/forum/viewtopic.php?f=4&t=51779 

Any suggestions on how to do this from within a Cocoa app?

**Comment by iandol** [comment]
citeproc-java has a command line interface, and Scrivener bundles Java so that could be one possibility, but running citeproc-js directly seems better...

**Comment by cormacrelf** [comment]
I'm rewriting this in Rust, partly aimed at exposing FFI that would be trivial to link in a Cocoa app. Don't pull in a JavaScript runtime (or worse, a Java runtime that runs an embedded JavaScript runtime like citeproc-java does... or even worse,  triple-nesting by shelling out to `java -jar`) just yet.

https://github.com/cormacrelf/citeproc-rs

**Comment by iandol** [comment]
@cormacrelf — great news, thanks!

**Comment by fbennett** [comment]
@cormacrelf I don't know what Rust is, but a clean reimplementation of the CSL specification would be a very good thing. If I can be of any use answering questions etc very happy to help.
