### ISSUE TITLE
Formatting of multiple locators parsed from Zotero locator field 

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#90]
If I enter multiple types of locators into Zotero's locator field (e.g., `Chapter: 1, p. 10`) and the style has different formatting for different locator labels (e.g., differences for page, chapter, etc.), the formatting is not changed for each label. Instead, whatever formatting the first label uses is applied to all labels.

For example, in apa.csl, Chapter is set to `form="long"` whereas Page is set to `form="short"`, but a locator entered as `Chapter: 1, p. 10` renders as "Chapter 1, page 10" instead of the expected "Chapter 1, p. 10".

**Comment by fbennett** [comment]
Yes, the form chosen follows that of the "primary" label (chapter, in the example). There isn't a way of expressing that pattern in CSL, and "smart" locator evaluation isn't helping. There is a way to get this effect in `citeproc-js`. You won't like it much - it depends on an accidental "feature" that I just stumbled across while looking through past test fixtures that might relevant - but I think it should not cause problems for other styles. Try removing the `form="long"` attribute from the `cs:label` node that calls the `chapter` term. That should default to `long` on the primary term, then default to `short` for the remaining labels.

**Comment by fbennett** [comment]
I agree that this behavior sucks in general, though.

**Comment by fbennett** [comment]
@bwiernik Did that change (removing `form="long"`) fix things?

**Comment by bwiernik** [comment]
Yes. That's a doable workaround absent official support for multiple locators in CSL.
