### ISSUE TITLE
page-range-delimiter for page ranges with suffixes

### ISSUE THREAD

**Issue by adam3smith** [Juris-M/citeproc-js#92]
via https://forums.zotero.org/discussion/comment/322133/#Comment_322133
the page range 162a-165d does *not* convert the delimiter to an en-dash. Given that 162a and 165d individually would be treated as `is-numeric=true` and that there are no obvious downside, I think the page-range delimiter should extend to such ranges.

**Comment by cormacrelf** [comment]
Here's a reference parser that handles it correctly. (Although it doesn't convert to en-dashes on the output phase yet.)

https://github.com/cormacrelf/citeproc-rs/blob/master/citeproc/src/input/numeric.rs

**Comment by fbennett** [comment]
I figured out how to fix this without breaking other things - all tests pass. The code is local at the moment, but I'll push it out in a fresh release with a bunch of other small fixes fairly soon (within the next couple of days).

**Comment by fbennett** [comment]
Fixed in tagged release 1.1.211.
