### ISSUE TITLE
DOI suffix gets wrapped in link

### ISSUE THREAD

**Issue by frederik-elwert** [Juris-M/citeproc-js#95]
In a CSL style that has a suffix for the `doi` field, the suffix gets wrapped in the link:

The CSL looks like this:

```xml
<text variable="DOI" prefix="doi:" suffix=", "/>
```

and leads to this HTML output:

```html
doi:<a href="https://doi.org/10.1553/medievalworlds_no8_2018s126,">10.1553/medievalworlds_no8_2018s126,</a>
```

(The example is taken from the style chicago-author-date-de.)

As one can see, the generated `href` attribute includes the trailing comma, which makes the DOI resolution fail and thus breaks the link.

A test with citeproc-hs confirms that this is implementation specific to citeproc-js and can be seen in both Zotero and a server-side application.

**Comment by fbennett** [comment]
Fixed in tagged release 1.1.211.
