### ISSUE TITLE
container-title-short and collection-title-short from note

### ISSUE THREAD

**Issue by bwiernik** [Juris-M/citeproc-js#96]
Currently, citeproc-js picks up `container-title-short` from the `note` field for the purpose of parsing the main title versus subtitle to apply `uppercaseSubtitles` to the `container-title` variable. This works great. I am raising two issues here:

1. `container-title-short` from `note` or entered directly in CSL-JSON is not being rendered when `<text variable="container-title" form="short"/>" is called by a style. The supplied `container-title` is used instead.
1. `collection-title-short` is ignored entirely. (Though I realize after typing this that collection-title unlike container-title does not have a `-short` form in CSL-JSON https://github.com/citation-style-language/schema/blob/e295d632a7548470457761d63cb9dad561afa84d/csl-data.json#L302)

For the first issue, for example, the article item listed below should render in (Vancouver style)[https://raw.githubusercontent.com/citation-style-language/styles/master/vancouver.csl] as:

1. Campbell DT, Fiske DW. Main title. Container.

But instead it renders as:

1. Campbell DT, Fiske DW. Main title. Container: a title.

For the second issue, it's a bit unexpected that `collection-title` (as well as `original-title` and `reviewed-title` do not have corresponding `-short` forms that can be stored in CSL-JSON). This presents issues when styles attempt to use `form="short"` when rendering title variables other than `title` or `container-title` (e.g., https://forums.zotero.org/discussion/75366/accommodating-both-full-series-names-and-series-abbreviations#latest). For consistency of behavior (e.g., with using the Extra field in Zotero; more generally, how are clients supposed to provide short forms of variables other than title and container-title?), it would be good for `-short` forms to be available for all title variables. (Or even for all text variables?) @adam3smith @rmzelle What are your thoughts on this front?

This behavior would be relevant for rendering `form="short"` titles in `text` and other CSL fields and for applying the `uppercaseSubtitles` logic to other title variables. 

# CSL-JSON example with CSL variables already split out

## Chapter

```
[
	{
		"id": "http://zotero.org/users/1386342/items/THDMV7DH",
		"type": "chapter",
		"title": "Main title",
		"source": "Zotero",
		"collection-title": "Series: a title",
		"collection-title-short": "Series",
		"container-title": "Container: a title",
		"container-title-short": "Container",
		"language": "en",
		"author": [
			{
				"family": "Campbell",
				"given": "Donald T"
			},
			{
				"family": "Fiske",
				"given": "Donald W"
			}
		]
	}
]
```

## Article

```
[
	{
		"id": "http://zotero.org/users/1386342/items/THDMV7DH",
		"type": "article-journal",
		"title": "Main title",
		"source": "Zotero",
		"collection-title": "Series: a title",
		"collection-title-short": "Series",
		"container-title": "Container: a title",
		"container-title-short": "Container",
		"language": "en",
		"author": [
			{
				"family": "Campbell",
				"given": "Donald T"
			},
			{
				"family": "Fiske",
				"given": "Donald W"
			}
		]
	}
]
```

# CSL-JSON example with CSL variables in `note`

## Chapter

```
[
	{
		"id": "http://zotero.org/users/1386342/items/THDMV7DH",
		"type": "chapter",
		"title": "CONVERGENT AND DISCRIMINANT VALIDATION BY THE MULTITRAIT-MULTIMETHOD MATRIX",
		"page": "25",
		"source": "Zotero",
		"note": "collection-title: Series: a title\ncollection-title-short: Series\ncontainer-title: Container: a title\ncontainer-title-short: Container",
		"language": "en",
		"author": [
			{
				"family": "Campbell",
				"given": "Donald T"
			},
			{
				"family": "Fiske",
				"given": "Donald W"
			}
		]
	}
]
```

## Article

```
[
	{
		"id": "http://zotero.org/users/1386342/items/THDMV7DH",
		"type": "article-journal",
		"title": "CONVERGENT AND DISCRIMINANT VALIDATION BY THE MULTITRAIT-MULTIMETHOD MATRIX",
		"page": "25",
		"source": "Zotero",
		"note": "collection-title: Series: a title\ncollection-title-short: Series\ncontainer-title: Container: a title\ncontainer-title-short: Container",
		"language": "en",
		"author": [
			{
				"family": "Campbell",
				"given": "Donald T"
			},
			{
				"family": "Fiske",
				"given": "Donald W"
			}
		]
	}
]
```

**Comment by fbennett** [comment]
Will look into these. I thought I had covered (1) in the 1.1.211 tag, but I must have missed something.

**Comment by fbennett** [comment]
I've built tests for these cases, and they all seem to work correctly with current processor tag 1.1.212.

https://github.com/citation-style-language/test-suite/blob/master/processor-tests/humans/variables_ContainerTitleShort.txt

https://github.com/citation-style-language/test-suite/blob/master/processor-tests/humans/variables_ContainerTitleShort2.txt
