### ISSUE TITLE
citeproc-js ES Module

### ISSUE THREAD

**Issue by navalpatel384** [Juris-M/citeproc-js#97]
Many websites are now using ES Modules and some website build systems are not compatible with CommonJS imports. Would it be possible for there to be an ES Module version of citeproc-js for use in modern websites?

**Comment by fbennett** [comment]
If you can post a link to the requirements for an ES Module, I can take a look.

**Comment by navalpatel384** [comment]
Here are some resources describing ES Modules import/export syntax.

- [MDN Web Docs - Import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)
- [MDN Web Docs - Export](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export)

**Comment by fbennett** [comment]
So it looks like it would be like the Common JS layout, but with `export { CSL }` as the last line?

Just in case there are other issues (internal syntax requirements, etc), I probably shouldn't make the change. If you can file a pull request and can confirm that the code runs in your environment, happy to add it though.

(As for how the module would be imported, that's not my department. :)

**Comment by fbennett** [comment]
Development of `citeproc-js` dates back more than a decade, to the days before JIT compilation. I learned my way around the language while coding the processor. Much of the code was rewritten (some of it repeatedly) in the course of development, but the code base still reflects my own bad habits, and contains plenty of things that seems to make professionals cringe.

At the same time, putting together a pretty faithful implementation the the CSL spec, with extensions for some things CSL doesn't cover, has taken a decade of work, for which I have received a grand total of five tee-shirts, a some product stickers, and a laser pointer that I seem to have mislaid somewhere. Given those economics, we're probably stuck with the current code base for the immediately foreseeable future.

So it would definitely be worthwhile to work out how to deploy the CSL object as an ES Module, and I would definitely accept a pull request for that purpose, although I don't have time to work on it myself.

**Comment by fbennett** [comment]
Apologies @navalpatel384 : my response above wasn't terribly helpful. The line you flag was removed some time ago, and the repo contains two copies of the bundled processor code, one of which (``citeproc_commonjs.js``) is in Common JS format, and exports the ``CSL`` object statically as required. In Node,js you can fetch the current release with ``npm install citeproc``.

More recently, in a belated response to urging by @dsifford, the test runner has been recast in Node.js, with a watch mode to support style authoring. Usage notes are in the README.

**Comment by blackdwarf** [comment]
FWIW, I took the `citeproc_commonjs.js` file and just changed the last line to read `export {CSL};` and that actually worked in the rest of my code which is ES6 and uses `import` all over the place.

**Comment by fbennett** [comment]
Thanks - I see how that works. It looks like the export syntax of the two are incompatible. Would the thing to do be to separately publish a `citeproc_es6` package on `npm`?

**Comment by dsifford** [comment]
No. Because transpilers will just convert that syntax into the commonjs syntax. There’s no perceivable benefit for doing _just_ that.

**Comment by fbennett** [comment]
So status quo is fine?

**Comment by gangsthub** [comment]
Right now, there's a big CSL object that has everything on it. And we are exporting everything... This makes code-splitting tools senseless and we get 700KB of code (gzipped) when importing this tool.

![image](https://user-images.githubusercontent.com/6775220/59783471-7bce3b00-92c0-11e9-8f13-52b1791c05c5.png)

The solution would be to have export methods separately (from different files) to achieve code-splitting. You could still have `module.exports = CSL` and import the whole jungle. But check how libraries like RxJS are doing:

https://github.com/ReactiveX/rxjs/blob/master/src/index.ts

Their main file (regardless being a .ts file) becomes a bunch of `exports`.

Checkout Rollup, specifically the [Tree shaking](https://rollupjs.org/guide/en#tree-shaking) section. They explain how to achieve this by swithing to ESM

**Comment by fbennett** [comment]
It sounds like you are unfamiliar with the operation of CSL processors. They cannot be usefully split into small atomic units.

**Comment by gangsthub** [comment]
I'm one of it's users, not a mantainer, so take my comments with a pinch of salt. What do you mean by _usefully split_? Are there too many interdependencies?

**Comment by fbennett** [comment]
Yes, that's it. The logic of citation styles is a kind of rabbit-hole of interrelated conditions, and I don't really know how you would separate out the pieces. It might be possible, but it would take someone more well trained and more well paid than I. :-)
